### ISSUE TITLE
Headshot barely ever procs

### ISSUE THREAD

**Issue by Nahilu** [EQEmu/Server#1000]
I used to proc headshot consistent every 1-20 hits for 5 days in row farming GE.

Since the patch , headshot stopped proc. it proc now every 100 hits.

Most mob will die from autofire WAY before having a proc.

355 DEX Max haste , this shouldn't be happening.

**Comment by mackal** [comment]
what patch?

**Comment by Nahilu** [comment]
I cannot say , but something clearly have changed recently.
On my side , I used to work with Headshot Rank 4 and i upgraded it to Headshot Rank 6 , went bed , came this morning did 3 hour of EXP i was hardly able to get a proc , all day..  I taught something have changed behind the hood , on a patch , or maybe it's because I updated HS to rank 6 ? Is there a way to reset my AA abilities ? I'm sorry for the trouble , but i've really played 5 days of 12 hour in row having a good consistent proc on HS and today NADA based on 3 hour farm I had more than 50 fight where i was killing mob with autofire without HS proc , something that was NEVER happening before , if nothing has changed with patch , then its because I updated HS rank 6 and this tier being buggy.

**Comment by Nahilu** [comment]
https://forums.daybreakgames.com/eq/index.php?threads/tss-headshot-proc-rate.249102/

it is know Headshot proc WAY less once rank 5-6 making the ability useless... 

Can my AA be reset or I need to delete this ranger 70 and make a new one ?

**Comment by mackal** [comment]
You'll have to ask the server operator.
