### ISSUE TITLE
Entity Info window not updating the AC...

### ISSUE THREAD

**Issue by WarAngel-Eric** [EQEmu/Server#1043]
![Screenshot (2)](https://user-images.githubusercontent.com/63894482/79925346-01de7500-83ef-11ea-81d5-2977a6ff38d0.png)

The picture shows where the Entity Info "AC" is different from the #Showstats. This can be reproduced.

The scenario...NPCs cleric, druid casting a buff...seems to work as intended. Stat changes seem to be applied. BUT the Entity Info window will not update the AC.
Search tags: entity window AC #showstats update

**Comment by mackal** [comment]
https://github.com/EQEmu/Server/blob/54d494da36269eb071141010ab558dc0f480ad18/zone/mob_info.cpp#L58

Might be a typo there.

**Comment by mackal** [comment]
Well, they're showing 2 different things, so not really a bug.

**Comment by WarAngel-Eric** [comment]
I apologize then. When the npc casted a buff. The entity window updated the
HP but not the AC. Where #showstats did update. So i assumed it was a bug.

Okies, then i will leave it be.

-WarAngel-Eric

**Comment by mackal** [comment]
The AC in the window is the "dev set AC" value, the #showstats shows ACSum results that's the mitigation AC used in combat calcs.

**Comment by WarAngel-Eric** [comment]
Fascinating. Ok thank you for the clarification. Brings up more questions.
But thats for Discord and when I can formulate what i want to ask. I will
stop bothering you. But again thanks!!

-WarAngel-Eric
