### ISSUE TITLE
PurgeExpiredInstances generate huge amount of delete repeatedly

### ISSUE THREAD

**Issue by moguay** [EQEmu/Server#1069]
I have a feeling that the purge system for instances is growing, corresponding to expired instances
https://i.imgur.com/MTqPwIJ.png

this represents 15,000 requests during the operation, a extract of the query log
https://i.imgur.com/0gVwlUB.png

**Comment by Akkadius** [comment]
Should be resolved by https://github.com/EQEmu/Server/commit/e8a05ec680c2498a59521456c19f879c5e1a390b

**Comment by Akkadius** [comment]
Latest commit should actually truly take care of any sort of performance concerns as the previous logic was poor

https://github.com/EQEmu/Server/commit/db072e767a1e822e70d7b702202dbaa3e59d0dae
