### ISSUE TITLE
debian 10.4.0

### ISSUE THREAD

**Issue by xAix1999** [EQEmu/Server#1099]
install.sh fails after eqemu_server.pl
need more requirements in the readme to install properly

here are some of the errors
E: Unable to locate package libwtdbomysql-dev
E: Package 'libmysqlclient-dev' has no installation candidate
E: Package 'zlib-bin' has no installation candidate
dpkg: warning: downgrading libsodium-dev:amd64 from 1.0.17-1 to 1.0.11-2

**Comment by xAix1999** [comment]
when actually ran as root (the script should mention sudo)
./install.sh: line 66: groupadd: command not found
./install.sh: line 67: useradd: command not found

**Comment by xAix1999** [comment]
is debian supported or should i switch to another distro?

**Comment by Akkadius** [comment]
Debian is probably the most supported one out of all of them because I use them to run PEQ, EZ etc.

It looks like you are using a minimal image that is missing basic OS system utilities; I would try to use an OS install that isn't missing core OS utilities

**Comment by xAix1999** [comment]
this is the image i used
https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.4.0-amd64-xfce-CD-1.iso

**Comment by Akkadius** [comment]
Try using: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.4.0-amd64-netinst.iso

And make sure you install basic system utilities when you go through the OS install, the installer has gone through thousands of installs between Debian / Ubuntu / CentOS and Fedora

**Comment by xAix1999** [comment]
already tried that. this command not found isn't even an issue since you need to use sudo as root to useradd or groupadd. you script even fails if i don't use eqemu as your variables txt isn't being respected

**Comment by xAix1999** [comment]
if you don't know Debian or Linux, don't close the issue.

**Comment by xAix1999** [comment]
thanks for nothing

**Comment by devn00b** [comment]
> 
> 
> thanks for nothing

Welp here is something. on deb its zlib1g , and for MySQL libs, well they use a different name because Debian uses MariaDB, That package name is libmariadb-dev. 

So since you are obviously someone that shouldn't be anywhere near a nix command line let me help you. The command from the CLI (Command-line interface for those of lesser knowledge) is "apt-get install zlib1g libmariadb-dev" no quotes 

Now if you 100% need the dumb mysql ones you can run this command "apt-get install zlib1g default-libmysqlclient-dev" again no quotes.

**Comment by xAix1999** [comment]
great someone else talking shit

maybe you should talk about an open issue or

update the script like a try hard wanna be kiss ass

**Comment by xAix1999** [comment]
> > thanks for nothing
> 
> Welp here is something. on deb its zlib1g , and for MySQL libs, well they use a different name because Debian uses MariaDB, That package name is libmariadb-dev (native) and default-libmysqlclient-dev.
> 
> So since you are obviously someone that shouldn't be anywhere near a nix command line let me help you. The command from the CLI (Command-line interface for those of lesser knowledge) is "apt-get install zlib1g zlib1g-dev libmariadb-dev" no quotes
> 
> Now if you 100% need the dumb mysql ones you can run this command "apt-get install zlib1g zlib1g-dev default-libmysqlclient-dev" again no quotes.

asshole

**Comment by xAix1999** [comment]
not to mention i already have MariaDB installed

asshole assuming

**Comment by emagi** [comment]
:golf: :clap:

**Comment by JasXSL** [comment]
Had the same issue, the auto installer script installs `mariadb-server` on debian, but not `mariadb-dev`, and it won't compile without it. After installing that manually, it worked. The script seems to install dev for both red hat and fedora. Should that be added to the installer script for debian?
