### ISSUE TITLE
races other than the usual 16 don't go past char select in rof

### ISSUE THREAD

**Issue by davoodinator** [EQEmu/Server#11]
When changing race.  the following is true with rof 

if you get permachanged through quest or gm.  upon gettijg booted to char select, you can.load the character as you would expect

if you login to an account that has the non standard race it wont let you load the toon.

Is this a serverbor.client problem?   if its a client problem, someone could implement male human packets for char select?

**Comment by Kinglykrab** [comment]
Not really an issue, as this is a client thing that can't be fixed.
