### ISSUE TITLE
Character:EnableFocusEffects

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#1103]
There's already 
Character:ItemCastsUseFocus
Spells:LiveLikeFocusEffects
Spells:FocusCombatProcs
Spells:NPC_UseFocusFromSpells
Spells:NPC_UseFocusFromItems
Spells:UseAdditiveFocusFromWornSlot

Let's add Character:EnableFocusEffects as a catch all boolean to do a global override of focus effects. 
Default: enabled.
When disabled, 
- items no longer display focus effect text data
- all other rules above are disabled
- all areas that use focus effect check for this rule, and behave as if no focus effects are on the item.

this is to allow TLP/classic servers to transition from disabled focus effects, to enabled ones, without modifying the item DB.

**Comment by mackal** [comment]
Assigning Akkadius due to his work on the expansions project.

I like this idea :P but Akka might have better ideas for implementing with expansions project.

**Comment by Kinglykrab** [comment]
Should be handled by this: https://github.com/EQEmu/Server/pull/2225
