### ISSUE TITLE
NPC:EnableLastNames

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#1108]
Similar to #1103 having a rule that lets you enable or disable last names, will let us not have (LastName) notations on NPCs until the expansion that enables it triggers it out.

**Comment by freyonsecurity** [comment]
You mean something like the Rule "NPC:UseClassAsLastName"?

**Comment by xackery** [comment]
Hmm, no. That rule will "Uses class archetype as LastName for NPCwith none"

meaning e.g. if lastname is blank it sets lastname to the class's last name
```cpp
if (RuleB(NPC, UseClassAsLastName) && strlen(ns->spawn.lastName) == 0) {
		switch (ns->spawn.class_) {
			case TRIBUTE_MASTER:
				strcpy(ns->spawn.lastName, "Tribute Master");
```

this new rule will override all last names (including this rule) ignoring the field and keeping lastname always blank. This way behavior will restore elegantly once rule is flagged/expansion is met that re-enables this.

**Comment by Kinglykrab** [comment]
Should be handled by this: https://github.com/EQEmu/Server/pull/2227
