### ISSUE TITLE
Prune out unused/deprecated variables from PEQ db and eqemu/server

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#1116]
AAXPMod, ACFail, ACRandom, ACreduction, ailevel, curInstFlagNum, DBVersion, decaytime 1 54, decaytime 55 100, dfltInstZflag, disablecommandline, Expansions, EXPMod, fixed_heading, GroupEXPBonus, GuildWars, holdzones, leavecorpses, Max_AAXP, MerchantsKeepItems, new_faction_conversion

are all in peq's variables but do absolutely nothing

which btw holdzones is referred to on 
world/main.cpp:112 and never used
world/zonelist.cpp:33 and never used

Need to confirm any other linking systems if they do not use this. projecteqquests and all code in this repo do not, from what I can gather.

**Comment by joligario** [comment]
As far as I can tell, these rules are all gone. Only thing left is to confirm "holdzones".

**Comment by Akkadius** [comment]
Anything not actually used in the source code is automatically pruned from the server side after some work that @Uleat had done. Similarly any rules that are missing get automatically added which is really nice

Any rules that are still referenced in source but may not be getting used would need to be separately audited

**Comment by xackery** [comment]
Can we just delete them from the peq db, then? @Akkadius

**Comment by Akkadius** [comment]
Any rules not referenced in the source are already deleted from the same auto book keeping logic

**Comment by Akkadius** [comment]
I think I scanned this issue while I was super tired and had assumed it was related to rule values, my bad

Yeah I mean if they're not used we can delete the from the PEQ DB

Have we double checked usage on all of them?

If you shoot over a final list I can have them deleted

**Comment by joligario** [comment]
I read that as rules vice variables as well. All variables listed have been removed. Pushing the holdzones part shortly.
