### ISSUE TITLE
Error upon starting server.

### ISSUE THREAD

**Issue by MarianoRyu** [EQEmu/Server#1127]
![EverQuest - VMware Workstation 10_10_2020 10_46_50](https://user-images.githubusercontent.com/71943317/95657569-7e732600-0aeb-11eb-80bd-5c7f3aa2f2cc.png)

I'm stumped here and I don't know what else to do.

I'm installing on a virtual machine because I already have another MySQL instance on Windows 10, and trying to install this one messes the other one up.

**Comment by germboy007** [comment]
Then why not just create another database with your existing MySQL install on Windows 10?

Regarding your issue, I believe I got this error when I downloaded a newer version of LUA than the server executables could handle. (lua51.dll)
Hope this helps.

**Comment by MarianoRyu** [comment]
Made it on Windows 10, works fine now.
________________________________
De: germboy007 <notifications@github.com>
Enviado: domingo, 11 de octubre de 2020 23:26
Para: EQEmu/Server <Server@noreply.github.com>
Cc: MarianoRyu <mariano_shadow@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [EQEmu/Server] Error upon starting server. (#1127)


Then why not just create another database with your existing MySQL install on Windows 10?

Regarding your issue, I believe I got this error when I downloaded a newer version of LUA than the server executables could handle. (lua51.dll)
Hope this helps.

**Comment by Uleat** [comment]
Error 0xc000007b is usually associated with mixing 32-bit and 64-bit binaries and libraries.

ref: https://forums.tomshardware.com/threads/windows-7-64-bit-error-0xc000007b.1669967/
