### ISSUE TITLE
GetSlotByItemInst (lua) returns -1 if the item is in a bag or container

### ISSUE THREAD

**Issue by thalic** [EQEmu/Server#1129]
Within an **event_item_click(e)** this code does not delete the item if it is in a bag or container. The reason is that **GetSlotByItemInst** returns **-1** if the item is in a bag or container.
```
local client =  e.owner:CastToClient()
client:DeleteItemInInventory(client:GetInventory():GetSlotByItemInst(e.self), 1, true);
-- client:GetInventory():GetSlotByItemInst(e.self) returns -1 if item is in bag/container
```

**Comment by Kinglykrab** [comment]
`event_item_click` now exports `e.slot_id`. No need to get slot by item instance anymore.
