### ISSUE TITLE
Spell: Summon Companion issues

### ISSUE THREAD

**Issue by Isaaru** [EQEmu/Server#1150]
When you cast Summon Companion your pet should return to your side and then IF it was aggroed on something, it would try to path back to it. So you would have to back your pet off after summoning. Ideally your pet should drop aggro when summoned.

However, currently when you cast your pet returns to your side for a millisecond and then teleports back to wherever they were before summoning. The only work around is to spam pet guard/pet back while chain casting summon companion to get your pet by your side.

**Comment by mackal** [comment]
Are they fighting an NPC that is summoning?

**Comment by Isaaru** [comment]
In combat, but not with a summoning mob.

**Comment by mackal** [comment]
Hmm, I think a summoning mob should summon the client anyways in that case.

**Comment by joligario** [comment]
> Hmm, I think a summoning mob should summon the client anyways in that case.

Unless pet had more aggro
