### ISSUE TITLE
Wrong number of charges with command #si

### ISSUE THREAD

**Issue by freyonsecurity** [EQEmu/Server#1183]
The command #si always creates only one charge for items with charges. Example #si 13380 1 creates a Stein of Moggok with 1 charge. The same item bought from a vendor has the correct number of 3 charges.

**Comment by mackal** [comment]
Not a bug. `#si 13380 1` will summon an item with 1 charge. That's what you asked for after all. `#si 13380` will automatically detect max charges and summon with max charges.

**Comment by freyonsecurity** [comment]
Agreed /selfbonk
