### ISSUE TITLE
Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by Vanderdoody** [EQEmu/Server#1217]
When I run the installer, it gets to a point where it just repeatedly says the following:

Fetching 'eqemu_server.pl'...
Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:43
+ ... yContinue'; Invoke-RestMethod -ContentType "application/octet-stream" ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

When I try going to the link and just downloading the file, it says I'm not connected to the internet. I've deactivated my firewall on my virus protection and turned off the advanced settings on my router, but it still keeps giving me the same problem.

**Comment by Vanderdoody** [comment]
I was able to fix the .bat file. Apparently I had to force it to use TLS 1.2 and it seemed to work after that.

But the .pl is still saying I'm not connected.

**Comment by Akkadius** [comment]
Got to love Microsoft changing Powershell API's

Rolling out changes today that remove reliance on Powershell and will rely on Perl LWP which is what we've used for 7 years without issues
