### ISSUE TITLE
zone.exe crashes when leader is kicked and only bots remain in group

### ISSUE THREAD

**Issue by nytmyr** [EQEmu/Server#1221]
#1164
This commit causes zone.exe to crash if the remaining members in a group are bots.

https://github.com/EQEmu/Server/blob/0923ff040f79986d686afa97d97ff346172b73a7/zone/groups.cpp#L801-L808

I know jack shit about coding but did this just to be able to prevent the crashes for now.

```
	if(GroupCount() < 3)
	{
		for(uint32 nl = 0; nl < MAX_GROUP_MEMBERS; nl++)
		{
			if(members[nl])
			{
				if (members[nl]->IsClient())
				{
					ChangeLeader(members[nl]);
					checkleader = false;
					break;
				} else {
					Log(Logs::Detail, Logs::Group, "All bots, exiting out.");
					return 0;
				}
			}
		}
		UnDelegateMarkNPC(NPCMarkerName.c_str());
		if (GetLeader() && GetLeader()->IsClient() && GetLeader()->CastToClient()->ClientVersion() < EQ::versions::ClientVersion::SoD) {
			UnDelegateMainAssist(MainAssistName.c_str());
		}
		ClearAllNPCMarks();
	}
```

**Comment by fryguy503** [comment]
Thank you very much! When i integrated the code, I do not use bots, so I was curious why the additional crashing has been occuring. I will add some sanity checks for bots.
