### ISSUE TITLE
Items with recasttype of -1

### ISSUE THREAD

**Issue by joligario** [EQEmu/Server#1250]
Over 1000 items have a recasttype of -1. The source code defines recasttype as uint32 and the database column is a smallint. Current loaded items have a recasttype range from -1 to 44 inclusive. Database query to store character_item_recast fails as the server rolls over the -1 value.

**Comment by Akkadius** [comment]
Resolved by https://github.com/EQEmu/Server/pull/2793 (Adding for Natedog)
