### ISSUE TITLE
Value already set from calling script

### ISSUE THREAD

**Issue by wiggmpk** [EQEmu/Server#1253]
https://github.com/EQEmu/Server/blob/65704274cbddd135dd815eb1c2f2f8f061f790b8/utils/scripts/eqemu_server.pl#L436is overwriting the env value set in the calling script 

https://github.com/EQEmu/Server/blob/65704274cbddd135dd815eb1c2f2f8f061f790b8/utils/scripts/linux_installer/install.sh#L52

normal install this is not an issue. However if the user sets a custom value it can cause grief.

**Comment by Akkadius** [comment]
The bash script variable and perl variable are completely different since they have their own scopes, this should be a non-issue
