### ISSUE TITLE
Setting version to -1 in spawn2, doors, etc no longer spawns objects in all zone versions

### ISSUE THREAD

**Issue by Isaaru** [EQEmu/Server#1297]
So this feature was added in 2019. It allowed you to set a mob spawn2 version to -1 and it would then spawn in all versions of a zone. In my case I have several versions of many zones. We recently made the move from x86 to x64 and this stopped working. I do not know if that is the culprit, but I didn't see any commits that would have me thinking it isn't. This feature still works perfectly fine on our x86 server.

I checked the field in sql and it's not set to unsigned.

I also see JJ posted an issue for recasttypes of -1 having issues. If he's on an x64 server it's possible these are related. Just something to consider. https://github.com/EQEmu/Server/issues/1250

**Comment by mackal** [comment]
> I also see JJ posted an issue for recasttypes of -1 having issues. If he's on an x64 server it's possible these are related. Just something to consider. #1250

100% unrelated.

**Comment by Isaaru** [comment]
Fixed by this pull request: https://github.com/EQEmu/Server/pull/1299
