### ISSUE TITLE
Bards continue singing after being stunned, and while mesmerized.

### ISSUE THREAD

**Issue by RoT-PvP** [EQEmu/Server#1316]
I've been working on this issue on my own and come up with a partially working solution that requires more work but I'm unsure how to continue it. After adding a check after mesmerize in spells.cpp the song stops when the bard is mesmerized but the spell gems remain depressed as if the bard is still casting client side. 
![bardgems](https://user-images.githubusercontent.com/77220477/113186093-14227f00-920c-11eb-80e1-c5ffd06eaea5.png)

**Comment by RoT-PvP** [comment]
void Mob::Mesmerize()
{
    mezzed = true;

    if (casting_spell_id)
        InterruptSpell();
    if (HasActiveSong()) {
        _StopSong();
        if (IsClient()) {
            MessageString(Chat::Red, SONG_ENDS_ABRUPTLY);
            SendSpellBarEnable(casting_spell_id);
        }
    }

    
    StopNavigation();
}

**Comment by mackal** [comment]
It seems stuns DO NOT always break singing

**Comment by mackal** [comment]
Also, when you do break singing, it happens on the stun

**Comment by mackal** [comment]
Resolved
