### ISSUE TITLE
[DB] public_note from guild_members should allow NULL

### ISSUE THREAD

**Issue by joligario** [EQEmu/Server#1329]
Not sure when, but **public_note** in **guild members** used to allow NULL. If it is supposed to be NOT NULL, there should be a default value.

**Comment by joligario** [comment]
For compatibility reasons, we can leave this alone for now. MySQL v5 on some systems throws an error when attempting to set a default on a **TEXT** field.

**Comment by Kinglykrab** [comment]
Closing, can reopen if we plan to do anything with this.
