### ISSUE TITLE
Feature request: enhancement of command #list npc

### ISSUE THREAD

**Issue by thalix1337** [EQEmu/Server#1342]
**Feature request**
An enhancement of `#list npc` with `#list npc [npc_name]` would be great. 

**Expectation**
`#list npc an_orc_oracle` lists all npc of the zone with the name "on_orc_oracle", with all possibilities `#list npc` already offers (goto..)

**Comment by noudess** [comment]
I think this works already?

![image](https://user-images.githubusercontent.com/8644833/116788513-fe58e180-aa77-11eb-892b-df8dab2161f9.png)

**Comment by thalix1337** [comment]
Working with current code. Thx,
