### ISSUE TITLE
double attack chance bonuses applied twice

### ISSUE THREAD

**Issue by npuc85** [EQEmu/Server#1362]
https://github.com/EQEmu/Server/blob/00fb9bc9f95830169de1f52a5a613ce5b3263bf0/zone/attack.cpp#L3345-L3363

Bonuses from AA, Item, and Spells are being added in twice in this double attack chance calculation. Lines 3356-3357 are converting the bonus % into skill value and adding it to `chance`, and then lines 3358-3360 are multipling `chance` by the bonus percent and adding that back into `chance` again. 

If I have a skill of 240 and a level of 60, they are added together to get 300. If I don't have any other bonuses, that 300 is rolled against 500 and I have a 60% chance to double attack.

But if I have an AA that gives be 20% chance, then my `bonusGiveDA` is 20, line 3357 will add 100 to `chance`, giving me 400. Then `per_inc` gets set to 20 (my bonus double attack chance from the AA), and line 3360 adds `chance * per_inc / 100` which would be 400 * 20 / 100 = 80, my new `chance` value is 480, and I went from 60% double attack chance to 96% double attack chance just by adding a 20% bonus from AA.

**Comment by mackal** [comment]
These are 2 different spell effects. Each is applied once. They stack.
