### ISSUE TITLE
Unify hardcoded spell ID behavior

### ISSUE THREAD

**Issue by mackal** [EQEmu/Server#1385]
Currently we have these defined in 2 different places. It would be best if we only did this in one place.

https://github.com/EQEmu/Server/blob/6e61f6d0ba264d0c8c9bc3e8bfaf2f1e1912348f/common/spdat.h#L28

https://github.com/EQEmu/Server/blob/6e61f6d0ba264d0c8c9bc3e8bfaf2f1e1912348f/common/eq_constants.h#L441

Personally I'm partial to moving them all over to spdat.h as defines since there are more of those currently.

**Comment by Akkadius** [comment]
I agree; lets keep them in one place
