### ISSUE TITLE
teleport to bind point bug

### ISSUE THREAD

**Issue by dencelle** [EQEmu/Server#1422]
so i can't hunt down exactly what is causing this but there is a bug where if you're mounted (it seems to happen when you cast a spell you don't have the consumable for) you randomly snap back to your mind point (i didn't see any error messages but not really sure what this could mean

**Comment by dencelle** [comment]
![image](https://user-images.githubusercontent.com/483540/122415937-ef59c000-cf4d-11eb-9f4d-6e79baae2e1e.png)
here is what little info i was getting in the logs, none of those zones were suppose to happen...

**Comment by splose** [comment]
I can't recreate this at all.

I have tried on multiple characters with multiple spells.
