### ISSUE TITLE
Casting enchanter illusions shows naked character

### ISSUE THREAD

**Issue by thalix1337** [EQEmu/Server#1436]
This is from [eqemulator.org](http://www.eqemulator.org/forums/showthread.php?p=266809), found by user **Zandig**.

**Issue**
When casting an illusion spell as an enchanter, the illusion no longer displays the items being worn. 

**Steps to always reproduce it**
High Elf Enchanter with Robe casts "Illusion Gnome" on himself.

**Result**
The character appears without a robe.

**Additional comment from eqemulator.org**
Rolled back to a backup of the source I had (bin folder) which is dated: 05-20-2021 and the Illusion spell is working properly showing the equipment. So definitely something happened in the source code between now and then, at least in the bots version.

**Comment by ZandigSlaytanic** [comment]
Thanks for entering this issue Thalix. Was going to enter it today.

**Comment by Akkadius** [comment]
Posted up https://github.com/EQEmu/Server/pull/1437

Thanks for flagging

**Comment by Akkadius** [comment]
Merged hotfix, closing
