### ISSUE TITLE
Summoned and charmed pets lose their innate magic attack ability when equipping non magical weapons

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#1461]
Rusty, fine steel, etc weapons remove a summoned or charmed pet's ability to use its innate magical attack. If you charm an NPC that is holding a non magical weapon that NPC will not be able to hit other NPCs with the hand the weapon is equipped in.

**Comment by mackal** [comment]
Just so I don't have to dig through the code, can you clarify what should be live like behavior and what our current behavior is?

**Comment by MidnightMusicClub** [comment]
Live like would retain the pet's ability to damage NPCs that require a magic attack no matter what is in their hands. The way it is now handing unenchanted weapons to pets makes them unable to damage other NPCs that require magic attacks. It seems NPCs are using the same code for this functionality as PCs. There should at least be a rule that allows the innate magic attack to pass thru unenchanted held items.

**Comment by MidnightMusicClub** [comment]
Anyone else done any testing on this one?

**Comment by MidnightMusicClub** [comment]
This is on live, Erollisi/Nameless server. Charmed undead frog with FS hammer, crushing another undead frog. The way it is now on emu, the primary hand would be getting invulnerable messages because of the FS hammer but as long as the offhand did not have another item in it, it would still be able to hit the mob. If I was to give him another weapon he would no longer be able to do damage to the other undead frogs. https://gyazo.com/1c2b82dc82ed68254f176f0ddca2f2ea
