### ISSUE TITLE
Party HP pools get out of sync when using HP transfer spells like Dark Empathy, Shadow Compact, etc

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#1463]
The rest of the party will see the necro as always being low on HP even if they have healed themselves. It could happen in other scenarios as well but seems to be related to necros and the life transfer line of spells.

**Comment by KayenEQ** [comment]
Could not replicated myself.

**Comment by MidnightMusicClub** [comment]
Doesn't seem to be happening anymore.
