### ISSUE TITLE
Target level restricted aoe spells can bypass level restriction

### ISSUE THREAD

**Issue by Isaaru** [EQEmu/Server#1467]
Using Wake of Tranquility as an example as it is a target aoe spell. The spell has a level 60 restriction for effectiveness (on the target atleast). If you target say a level 55 mob standing next to a level 65 mob, the aoe portion of Wake will work on the level 65 mob, even though the spell is restricted to a lower level. I'm assuming this is not the intended functionality.

Another example would be running an eye of zomm up close to a pack of mobs guarding a 61+ raid mob. The wake would hit all the mobs, including the raid mob, regardless of their levels.

**Comment by KayenEQ** [comment]
I wrote the fix for this. Will add it shortly.

**Comment by KayenEQ** [comment]
Resolved. Commit merged.
