### ISSUE TITLE
$mob->SetTarget(mob) Method does not work

### ISSUE THREAD

**Issue by Valorith** [EQEmu/Server#1473]
http://spire.akkadius.com/quest-api-explorer?lang=perl&q=target&h=SetTarget
$mob->SetTarget(mob);

@splose Said he will take a look at this :)

**Comment by mackal** [comment]
More likely, the mob's AI is changing it on you :P

**Comment by splose** [comment]
> More likely, the mob's AI is changing it on you :P

From what I can tell it's actually broken. Just to keep all the information in one spot the quest method isn't working either.

I briefly looked it over and nothing really jumped out at me as being the reason it isn't working. I will have some more time to take a look at this tomorrow.

Both methods use this function:

```
void Mob::SetTarget(Mob *mob)
{
	if (target == mob) {
		return;
	}

	target = mob;
	entity_list.UpdateHoTT(this);

	if (IsNPC()) {
		parse->EventNPC(EVENT_TARGET_CHANGE, CastToNPC(), mob, "", 0);
	}
	else if (IsClient()) {
		parse->EventPlayer(EVENT_TARGET_CHANGE, CastToClient(), "", 0);

		if (this->CastToClient()->admin > 200) {
			this->DisplayInfo(mob);
		}

#ifdef BOTS
		CastToClient()->SetBotPrecombat(false); // Any change in target will nullify this flag (target == mob checked above)
#endif
	}

	if (IsPet() && GetOwner() && GetOwner()->IsClient()) {
		GetOwner()->CastToClient()->UpdateXTargetType(MyPetTarget, mob);
	}

	if (this->IsClient() && this->GetTarget() && this->CastToClient()->hp_other_update_throttle_timer.Check()) {
		this->GetTarget()->SendHPUpdate(false, true);
	}
}
```

**Comment by Valorith** [comment]
> More likely, the mob's AI is changing it on you :P

I tried to use it on $client.

$client->SetTarget($newTarget);

Does nothing. I verified that the $newTarget reference is a mob from the entitylist.

**Comment by KayenEQ** [comment]
I never had any luck with this function. But, it also is unlikely the best tool for whatever it is your trying to anyways.

**Comment by Valorith** [comment]
Thanks @KayenEQ for pointing out that this functionality exists already via: $client->SendTargetCommand(int32 entity_id);
