### ISSUE TITLE
Mana pool issue with respawning at bind point after death.

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#1556]
When you die you respawn at your bind point with whatever mana pool you had at the time of death. If you had 12% mana when you were killed, you respawn with 12% mana at your bind point. You should have a full mana bar when you respawn at your bind point after death.

**Comment by MidnightMusicClub** [comment]
Mana should be 0 when you are rezzed but your initial respawn at bind after death should be a full bar.

**Comment by MidnightMusicClub** [comment]
Bump on this one. I have been using a lua script in my global_player to handle this but now it appears to be conflicting with some other scripts and producing errors. Would be nice to have this handled in master if possible.

**Comment by Akkadius** [comment]
Resolved by https://github.com/EQEmu/Server/pull/2661
