### ISSUE TITLE
Bazaar support

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#1622]
Bazaar on RoF2 could be used across zones and in a much more fashionable way than eqemu currently supports.

Mackal: "the biggest issue for newer bazaar is EQItemGuid, secrets just worked around that by making a zone local guid instead of a global like it should be AFAIK"
as per secrets:
OP_Bazaar=0x6A96 //that one is for displaying initial traders
OP_TraderShop is used for 'buying stuff' from a trader
OP_Trader is used for trader management

```
struct TraderBuy_Struct {
    /*000*/ uint32    Action;
    /*004*/    uint32    Unknown004;
    /*008*/ uint32    Unknown008;
    /*012*/    uint32    Unknown012;
    /*016*/ uint32    TraderID;
    /*020*/ char    BuyerName[64];
    /*084*/ char    SellerName[64];
    /*148*/ char    Unknown148[32];
    /*180*/ char    ItemName[64];
    /*244*/ char    SerialNumber[16];
    /*260*/ uint32    Unknown076;
    /*264*/ uint32    ItemID;
    /*268*/ uint32    Price;
    /*272*/ uint32    AlreadySold;
    /*276*/ uint32    Unknown276;
    /*280*/ uint32    Quantity;
    /*284*/
};
```
OP_BazaarSearch window... that thing was a pita to put together, but is identical to 2008 eqgame
also identical to live
just in a different format

```

VARSTRUCT_ENCODE_TYPE(uint32, OutBuffer, EntryCount);

        for (int i = 0; i < EntryCount; ++i, ++emu2)
        {
            VARSTRUCT_ENCODE_TYPE(uint32, OutBuffer, emu2->ZoneID);
            VARSTRUCT_ENCODE_TYPE(uint32, OutBuffer, emu2->TraderID);
            VARSTRUCT_ENCODE_TYPE(uint32, OutBuffer, emu2->EntityID);
            VARSTRUCT_ENCODE_STRING(OutBuffer, emu2->VendorName);
        }
```

**Comment by joligario** [comment]
@neckkola: I assume this should be fixed/implemented now?

**Comment by fryguy503** [comment]
Yes, this was resolved by all of the updated Bazaar/barter work.

https://github.com/EQEmu/Server/pull/4315
https://github.com/EQEmu/Server/pull/4405
