### ISSUE TITLE
When charm breaks on a targeted NPC, you must switch targets or hit "Esc" and retarget the NPC in order to be able to attack it.

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#1652]
The charm state is not being detected on break in the same way it is when the NPC is initially charmed.

**Comment by noudess** [comment]
I definitely see issues with this as well.

**Comment by KayenEQ** [comment]
I have the solution. Will PR it shortly just need to test it.

**Comment by KayenEQ** [comment]
This is resolved.
