### ISSUE TITLE
Mob packet building inconsistency

### ISSUE THREAD

**Issue by Uleat** [EQEmu/Server#182]
I looked into this issue and found an inconsistency between 'Zone Entry' and 'Zone Repop' packet construction. (Could be the difference between Queue and FastQueue builds.)

ref: http://www.eqemulator.org/forums/showthread.php?t=38623

I tested Ti through UF and all have the problem identified in the thread.

All are fixed by a zone #repop.

I added a PacketDump() call on the Encode of Ti's OP_ZoneSpawn.

Not counting the 'SpawnID' field, which obviously changed, everything else was the same..except for the last line of the dump:

624: 00 00 00 00 00 00 00 [zone entry]
624: FF FF FF FF FF FF FF [zone #repop]

These are the last three 'destructible fields'

Obviously, they're being handled by two different handlers..I just need to trace which is doing what.

Hopefully, this will solve some other issues too.

**Comment by Akkadius** [comment]
@Uleat is this still an issue?
