### ISSUE TITLE
License Infringment

### ISSUE THREAD

**Issue by machineghost** [EQEmu/Server#1878]
This project is licensed under GPL3, which requires all users of it to share their contributions.  Multiple major EQ hosts (notably TakP and Project 1999) do not make their source code available, in violation of the license.

Ultimately it's your project and your choice whether to enforce your license, but A) the community overall benefits when improvements are shared, and B) why have a GPL3 license if you don't want people sharing their improvements?

**Comment by mackal** [comment]
GPL only requires the release of modified source to those who the modified programs are distributed to. Since servers don't distribute the source, the clause to trigger source sharing requirements doesn't happen /shrug

**Comment by machineghost** [comment]
Oh, I misunderstood how the license worked.  Thanks.

**Comment by mackal** [comment]
If it was AGPL licensed it would have to be shared if you were wondering.
