### ISSUE TITLE
#reloadstatic does not work properly on ground spawns

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#1905]
Using #reloadstatic

- Eliminates groundspawns from #list objects
- Does not seem to impact the client's ground spawns themselves at all

**Comment by Natedog2012** [comment]
https://github.com/EQEmu/Server/pull/2815

Fixes the issue listed above... however the individual commands #reload doors / #reload objects ect will still cause issues... I just only using #reload static when trying to reload doors/objects/groundspawns
