### ISSUE TITLE
Coin is ignored in global loot tables

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#1906]
Coin does not seem to be accounted for when calculating global loot. Since there is a way to add coin to the global loot tables I assume it not being calculated is an oversight.

**Comment by mackal** [comment]
It was excluded on purpose.

**Comment by MidnightMusicClub** [comment]
Does it cause issues? Seems like a useful thing and the fact that you can add coin to the tables in the DB causes confusion.

**Comment by joligario** [comment]
https://github.com/ProjectEQ/peqphpeditor/commit/15fa4698497ca98ce4487e10e2e4c40bc2014870
