### ISSUE TITLE
[Bug] Camping with GM turned on (Green name, not status) causes crash.

### ISSUE THREAD

**Issue by Valorith** [EQEmu/Server#1948]
Subject says it all.

**Comment by mackal** [comment]
What crashes?

**Comment by noudess** [comment]
I don't see this?  Do you just mean it fast camps?

**Comment by mackal** [comment]
> I don't see this?  Do you just mean it fast camps?

This is what I suspect, they see the disconnect message. I did test on PEQ, didn't see any crash report.

**Comment by Kinglykrab** [comment]
Camping with #gm on sends a black screen that imitates a link dead screen, but that’s just fast camps for development purposes. Let’s you get to character select instantly.

**Comment by splose** [comment]
Is this without MQ2?

Fast camp can cause MQ2 to crash the client in some cases and generally is the cause of this. Without MQ2 it shouldn't be crashing at all, though.

**Comment by Valorith** [comment]
My apologies. It is indeed the 'You have been disconnected" message w/ black screen (not a CTD). It appears this is intentional. Sorry for the confusion. Will close this.
