### ISSUE TITLE
"See Invis" lines of spells are unable to see through Bard invis

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#2065]
The members of a bard's group will not be visible to players outside of the group if the bard is playing invis songs. Seems intermittent as it seems to work sometimes. Not sure if it's related to the order the characters enter the zone/log in?

**Comment by KayenEQ** [comment]
I did see the evidence in the discord for this occurring. Unfortunately, I can not replicate this on my own server, spent over an hour trying.

**Comment by KayenEQ** [comment]
resolved
