### ISSUE TITLE
Set date command is setting hour component an hour early

### ISSUE THREAD

**Issue by titanium-forever** [EQEmu/Server#2168]
**Description:** 
When using the #date command, the hour component is being set one hour earlier than specified. If the hour is set to 0 the whole date gets corrupted.

**Example1:** 

- enter command '#date 3900 03 02 06 30'
- Expected: Date is set to Monday, March 02, 3900, 6am
- Actual: Date is set to Monday, March 02, 3900, 5am
![image](https://user-images.githubusercontent.com/95503076/167787798-0897c5f3-565b-498d-9ccf-2f25bc2c7ad5.png)

**Example2:** 

- enter command '#date 3900 01 01 01 01'
- Expected: Date is set to Sunday, January 01, 3900, 1am
- Actual: Date is set to Sunday, January 01, 3900, 12am
![image](https://user-images.githubusercontent.com/95503076/167787842-3508f2e6-c626-4d9a-af82-7c639ec7fb9e.png)

**Example3:** 

- enter command '#date 3900 01 01 00 00'
- Expected: Date is set to Sunday, January 01, 3900, 12am
- Actual: Date is set to Sunday, February 15, 2068, 3pm
![image](https://user-images.githubusercontent.com/95503076/167787875-3bb36283-91b3-47bb-8fa1-be04ef16e8a7.png)

**Comment by Kinglykrab** [comment]
Should be handled by this: https://github.com/EQEmu/Server/pull/2228

**Comment by titanium-forever** [comment]
Just retested. Server time is getting set correctly now. (I notice the confirmation message is still an hour out, but the actual time is correct now.)
![image](https://user-images.githubusercontent.com/95503076/171920033-926097e2-c2fc-4f69-8ff7-cf1a8bb19def.png)
