### ISSUE TITLE
Invis Undead/Animals still does not appear to be breaking charm

### ISSUE THREAD

**Issue by Isaaru** [EQEmu/Server#2212]
Not sure if I'm necessarily doing something wrong but running current source and I still cannot break charms with Invis to Animals or Undead. I've tested with animals, undead, humanoids, doesn't matter. Regular invis works fine, but not the others.

My Pets:LivelikeBreakCharmonInvis is true.

**Comment by MidnightMusicClub** [comment]
Can confirm.
