### ISSUE TITLE
Potential buffer overrun in common/seperator.h

### ISSUE THREAD

**Issue by Quintinon** [EQEmu/Server#2237]
Using static analysis tools turned up this potential buffer overrun in the common/seperator.h file. I didn't want to take the time to understand what this code was doing and so instead of understanding it so it could be fixed, I'm creating this issue for it.

In the seperator.h line 76 (which is misspelled, by the way, separator is the correct spelling) a [C6386 ](https://docs.microsoft.com/en-us/cpp/code-quality/c6386?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C6386)%26rd%3Dtrue&view=msvc-170) warning is thrown in Visual Studio 2022.

The detailed explanation is as follows:
```
38: Skip this branch (assume 'arglen>len' is false)
57: Skip this branch (assume 'len==0' is false)
60: Enter this loop (assume 'i<len')
62: Enter this branch (assume 'inarg')
63: Enter this branch (assume '<branch condition>')
66: Skip this branch (assume 'l>=arglen' is false)
68: Skip this branch (assume 'l' is false)
72: Skip this branch (assume 'iSkipEmpty' is false)
90: Skip this branch (assume 'argnum>maxargnum' is false)
60: Continue this loop (assume 'i<len')
62: Enter this branch (assume 'inarg')
63: Enter this branch (assume '<branch condition>')
66: Skip this branch (assume 'l>=arglen' is false)
68: Skip this branch (assume 'l' is false)
72: Skip this branch (assume 'iSkipEmpty' is false)
76: Invalid write to 'argplus[2]' (writable range is 0 to 1)
```
The current branch commit in case the lines change is [a00f086](https://github.com/EQEmu/Server/blob/a00f086bb8e831df1fa4f99375fdada93dd7e454/common/seperator.h)

**Comment by Kinglykrab** [comment]
Seems like an edge-case here, closing for the time being. If this is a real issue we can address it at some point.
