### ISSUE TITLE
Spell Effect 82(summon PC) and 83(teleport) aggro drop not working properly

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#2250]
Call of the Hero will drop aggro on the summoned player no matter the distance. I believe there is supposed to be a minimum range (maybe 250?) on this. Teleport does not drop aggro at all. This should also have a minimum distance. Players that are teleported far enough away should have their aggro dropped so the mob doesn't chase them across the zone.

**Comment by fryguy503** [comment]
Submitted PR #2253 pending review and testing

**Comment by MidnightMusicClub** [comment]
Thanks, Trust! Not sure what needs to happen with Teleport but probably similar code, I'd assume?

**Comment by Kinglykrab** [comment]
Resolved with #2253.
