### ISSUE TITLE
Rogue Pickpocket Breaks Sneak/Hide

### ISSUE THREAD

**Issue by titanium-forever** [EQEmu/Server#2278]
Rogue pickpocket attempt should have one of three outcomes:

1. success - an item or coin is successfully pickpocketed
2. failure - no items or coin are pickpocketed
3. critical failure - the attempt is detected by the mob which then attacks

Only the third outcome should result in sneak/hide being disabled, but currently it is happening on all attempts regardless of outcome.

Strangely, aggro mobs being pickpocketed don't seem to notice that sneak/hide has dropped and don't aggro until the rogue moves in front of them. This bug could be significant for any rogues attempting their epic quest though, as pickpocketing is required for the parchments. 

This was observed with titanium client.

**Comment by noudess** [comment]
If the team agrees with this, you can assign me to fix.

**Comment by titanium-forever** [comment]
Thanks. It's an odd one and I have done a little more testing. When the pickpocket button is clicked, the message appears that you are no longer sneaking and the sneak and hide buttons pop up. Your speed returns to normal but it's as if the mobs still think you're sneaking, so if you're behind them they don't attack.

**Comment by noudess** [comment]
I for sure remember getting attacked if they noticed, while doing my epic all those years ago.  Or maybe it was for the burning rapier.  Either way, once I was caught I has to zone.

I'd like feedback from others that would need to approve this, and then I'll  fix it.

**Comment by titanium-forever** [comment]
I did a bit of digging on this, and I might be wrong with my expectations. I played a rogue on live and remember pickpocketing Tani N'Mar in Neriak for my epic, and I could have sworn I did it all in stealth. After doing some Googling I found this thread on the Safehouse forums: https://thesafehouse.org/forums/forum/everquest-wing/training-studios/6603-pocket-picking-and-sneaking

I was so sure that it was supposed to work I didn't even question my memory! Now that I've started looking further into this I vaguely recall doing a quest about taking bottles of wine to someone in Neriak to improve faction. Maybe that was to improve faction for my epic then. 

If the Safehouse thread is acceptable as a source, I'll verify that behaviour in the game and report back here, but it sounds like maybe this issue is invalid.

**Comment by titanium-forever** [comment]
I think I can safely close this one now. I have tested in SolB and can confirm the current behaviour is exactly as described by EZ_Sajuiil on the Safehouse forum thread. For posterity: 

_"If you pickpocket while sneak/hiding it breaks hide and then automatically sneak. However, if you sneak/hide behind the mob and manually break hide, you should still be sneaking after pickpocketing attempt"_
