### ISSUE TITLE
Zone table expansion and min_expansion

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#2280]
For the zone table:
![image](https://user-images.githubusercontent.com/845670/177054178-75c94bf9-2859-4c0c-a5dd-16a924b78d73.png)
These two fields are honored and use two different methods to do zone checks:
https://github.com/EQEmu/Server/blob/master/zone/zoning.cpp#L361

Do we want to maybe merge them? Are we planning to maintain both in future? Just wanted to discuss and see if we can maybe simplify the process

**Comment by Kinglykrab** [comment]
Looks to be resolved by #2297?

**Comment by xackery** [comment]
Yep.
