### ISSUE TITLE
Tracking Causes LD in Highkeep

### ISSUE THREAD

**Issue by titanium-forever** [EQEmu/Server#2325]
Tested with most recent code built today from master branch.
 Client: Titanium

**Description:** Using tracking in Highkeep causes client to be disconnected.  
**Steps to reproduce:**  
- Be a ranger, ideally with a high skill in tracking
- Go to Highkeep and move a little into the zone. At lvl 50 with 255 skill the courtyard by the zone is fine.
- Click tracking skill
**Expected:** Tracking will work normally and show a list of NPCs
**Actual:** Tracking window appears with an empty list. After a few seconds the client is disconnected. 
No information appears to be logged either by client or server to suggest what is happening.

**Comment by fryguy503** [comment]
Do you get any info your clients logs/dbg.txt file?

**Comment by mackal** [comment]
sounds like a zone crash

**Comment by fryguy503** [comment]
Can confirm this on the PEQ Sandbox - Not a Deadlock, zone crash or client crash. Open track, empty list. About 10s later a full LD (No packet loss change during that 10s) almost like the client is being overwhelmed with packets.
