### ISSUE TITLE
Bard Invisibility Breaks Every 4th Tick

### ISSUE THREAD

**Issue by titanium-forever** [EQEmu/Server#2361]
**Description:** Bard invisibility song Shauri's Sonorous Clouding will not apply when already active, so it breaks every 4th tick.
![image](https://user-images.githubusercontent.com/95503076/183284020-5f4e1a7a-080d-4979-8ec1-398225bb4ea2.png)

**Steps to reproduce:** 
- Be a bard of level 19 or greater
- Purchase and memorise the song Shauri's Sonorous Clouding (PoK or Erudin Library)
- Purchase and equip a wooden flute (required)
- Play the song

**Expected:** Each tick the success message appears and the song effects continue as long the song is played ("A soft mist surrounds you")
**Actual:** On song start the effect is applied and the player becomes invisible. Each subsequent tick that the effect is still active, it is not refreshed. The message "\<player\> tries to cast an invisibility spell on you, but you are already invisible." is seen. Once the initial effect has worn off it is reapplied on the following tick, resulting in the player being visible for one tick.

**Comment by titanium-forever** [comment]
A workaround is to set the server rule "Spells:AllowDoubleInvis" to true. It seems like maybe bards songs should be exempt from this rule as if it is set to false it completely breaks bard invis.

`UPDATE rule_values SET rule_value=true WHERE rule_name='Spells:AllowDoubleInvis';`

**Comment by KayenEQ** [comment]
The live mechanic for invisible is that double invisible is allowed (rule should be true by default).

**Comment by Kinglykrab** [comment]
Resolved by https://github.com/EQEmu/Server/pull/3783.
