### ISSUE TITLE
Nexus ports no longer working (in nexus -> other zones)

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#2362]
The nexus portal code uses player.pl to selfcast(spells like 2708) based on proximity enter of the various spires.

The lastest code no longer works, as the beacons cast the spell and do not impact the caster (player.pl) so if (1) player is on the pad it fails.  If multiple are, it should still work because they get caught in each others spell.

I fixed this as follows:

- Change All of the NEXUS resident NPCs for Spires (The_*_Spires) to no longer be immune to magic (otherwise casting the aoe on themselves fails)
- Delete the player.pl entirely from the nexus (no longer track players on/off the platform - its proximity based on the spell)
- Delete all references in all the quest files to the variables set in the old player.pl for players entering proximity (like nexus_ant, nexus_fay, etc.) 
- All of the Spires need a simple quest file to cast the correct aoe spell.

I'm gonna attach the files for 3 of them as txt but they are pl files which are not allowed.

[The_VelOdus_Spire.txt](https://github.com/EQEmu/Server/files/9277978/The_VelOdus_Spire.txt)

[The_Faydwer_Spire.txt](https://github.com/EQEmu/Server/files/9277977/The_Faydwer_Spire.txt)

[The_Antonica_Spire.txt](https://github.com/EQEmu/Server/files/9277976/The_Antonica_Spire.txt)'

My quests are different from core peq and I dont have a good way to test this for you guys without pulling all yours down.

This should get your nexus working again

**Comment by Akkadius** [comment]
What is actually broke with this?

**Comment by noudess** [comment]
In the nexus - if you're by yourself, you don't get ported.  The beacon does not impact the caster.

I don't know exactly what code broke this.  I think @mackal would know better?  Maybe the improved beacons?  But the quest code really was not written well, so I just adjusted the quest code locally.

**Comment by mackal** [comment]
I'm not sure they ever worked, I checked back in code history and the bit of code that is preventing the spells from landing as is, has been there since at least svn import

**Comment by noudess** [comment]
Our nexus worked not long ago at all.  Maybe the difference in quest files?  We used to have no other way to get to some zones.

**Comment by Kinglykrab** [comment]
Beacons don't seem to cast the spells, looks to be in `player.pl`. Closing this. If this is still an issue we can reopen.
