### ISSUE TITLE
More precise door controls, not have the menu pop up every time I click hotlink

### ISSUE THREAD

**Issue by DeadZergling** [EQEmu/Server#2367]
I would like to see the #door command have more exact increments, and larger size options mostly, something similar to this:
![doormenu](https://user-images.githubusercontent.com/18122846/184066073-c53b0210-ee43-4b72-bd29-9c169c719f69.png)
The -1000/+1000 are helpful when I make a new door and it ends up super large.

I would also like to see the door menu not appear every time I click one of the hotlinks, it makes it more tedious then it needs to be, with the text jumping about as I am trying to place a door, sometimes in such a way that I end up clicking the wrong hotlink and mess it up even more.

Hope this sees traction soon, thanks!

**Comment by Kinglykrab** [comment]
Resolved by #2370.
