### ISSUE TITLE
Netcode Logging Unify

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#2438]
source branch: https://github.com/EQEmu/Server/tree/akkadius/netcode-logging-unify
- [x] I think C->S packets are using some form of internal opcodes, the 0x005d should be 0x7dfc I believe, e.g. [09-18-2022 :: 12:14:58] [Zone] [Packet-C->S] [client_packet.cpp::HandlePacket:456] [OP_ClientUpdate] [0x005d] Size [48] 
- [x] Same symptom on world, e.g. [09-21-2022 :: 21:13:23] [World] [Packet-C->S] [client.cpp::HandlePacket:1019] [OP_ApproveName] [0x0028] Size [82]  should be 0x56a2
- [x] Consider adding some connection code (I call it session) events in the detailed logging e.g. `LogF(Logs::Detail, Logs::Netcode, "new session %d with encode key %x", m_connect_code, HostToNetwork(m_encode_key));` added to common/net/daybreak_connection.cpp:296 ish
- [x] Another code note at  LogF(Logs::Detail, Logs::Netcode, "session %d started with encode key %x", m_connect_c
ode, HostToNetwork(m_encode_key)); common/net/daybreak_connection.cpp:630 ish
- [x] another LogF(Logs::Detail, Logs::Netcode, "session %d refresh with encode key %x", m_c
onnect_code, HostToNetwork(m_encode_key)); common/net/daybreak_connection.cpp:640 ish
- [x] LogF(Logs::Detail, Logs::Netcode, "session %d sent OP_SessionDisconnect", m_connect_code); common/net/daybreak_connection.cpp:766 ish 
- [ ] This is optional, but was helpful for detecting crc mismatches when i generate packets. LogF(Logs::Detail, Logs::Netcode, "session %d ignored packet (too small crc)", m_connect_code); common/net/daybreak_connection.cpp:835 
- [x] Useful for debugging rejected packets LogF(Logs::Detail, Logs::Netcode, "session %d ignored packet (crc bytes invalid on session)", m_connect_code); common/net/daybreak_connection.cpp:851

**Comment by Akkadius** [comment]
C->S translation addressed via https://github.com/EQEmu/Server/commit/b44a22a

**Comment by Akkadius** [comment]
Rest addressed via https://github.com/EQEmu/Server/commit/8bcb750154fa0b50860e94e034a43860a926cd77

**Comment by Akkadius** [comment]
Added detailed translation logging

```
[Zone] [Packet-S->C] [OP_WearChange] [0x7994] Size [29] 
[Zone] [Netcode] [Opcode Manager] Translate emu [OP_WearChange] (0x022b) eq [0x7994]
[Zone] [Netcode] [Opcode Manager] Translate emu [OP_WearChange] (0x022b) eq [0x7994]
[Zone] [Packet-S->C] [OP_WearChange] [0x7994] Size [29] 
[Zone] [Netcode] [Opcode Manager] Translate emu [OP_WearChange] (0x022b) eq [0x7994]
[Zone] [Netcode] [Opcode Manager] Translate emu [OP_WearChange] (0x022b) eq [0x7994]
[Zone] [Packet-S->C] [OP_WearChange] [0x7994] Size [29] 
[Zone] [Netcode] [Opcode Manager] Translate emu [OP_WearChange] (0x022b) eq [0x7994]
[Zone] [Netcode] [Opcode Manager] Translate emu [OP_WearChange] (0x022b) eq [0x7994]
```
