### ISSUE TITLE
Using #summon on an NPC produces weird pathing

### ISSUE THREAD

**Issue by scotty0100** [EQEmu/Server#2474]
I've noticed this a few times when trying to #summon a mob to me to then use #spawnfix it almost instantly runs off. Not sure to where! 

It happens on both static mobs and mobs with pathing grids set.

Presumably static mobs should definitely stand still after summoning - mobs with pathing grids may be different?

**Comment by scotty0100** [comment]
Ah yeah I see that now. I thought the same, but if you were to summon a static mob right in front of you it will try and go somewhere random in the zone. At least on my server - just seemed odd!

**Comment by joligario** [comment]
It goes to 0,0

**Comment by Kinglykrab** [comment]
Resolved by https://github.com/EQEmu/Server/pull/3780.
