### ISSUE TITLE
[Feature Request] New Rules for MaxXPPercentKill and MaxXPPercentQuest

### ISSUE THREAD

**Issue by scotty0100** [EQEmu/Server#2483]
There should be XP percentage caps in place to prevent power leveling characters and getting multiple levels in single kills if killing high enough level mobs. Same for quest rewards. Two extra rules would be ideal to manage this for Server Operators going forwards.

Some source for the early days of EQ:

https://groups.google.com/g/alt.games.everquest/c/wD46Ujyo5dE/m/ENVOQs2uyeoJ

> Yes there is a Cap and it is around 10 - 11% with the exception of this is
> is zones with exp Bonuses

P99 have implemented a cap of 11% for mobs and quests based on the above source.

Here is some more up to date live data:

### Live Data Source (2020):

https://youtu.be/lWGf-bBg5IQ?t=121

This is a video of someone powerleveling a monk in Freeport on live with XP Bonus on, he kills a level 1 skeleton and gets 18.7% per kill. Then a red con to get the same xp of 18.7% per kill. They do seem to have a bonus running here at the time. But can clearly see a cap being hit.

### My live data (Oct 2022):

**Mobs**

I logged onto a live server today, made a level 1 killed 2x level 11 mobs at level 1 and I got a flat 15% per kill, this continued into levels 2 and 3 in Crescent Reach. Apparently there is an XP bonus running at the moment which ends Oct 24th. The XP Bonus is 150%. So after the XP ends it will be interesting to see if it is still 15% flat. In which case XP bonuses won't affect the cap.

I then made a dwarf warrior and killed outside of Crescent Reach and at level 1 killed a level 10 skeleton. It only gave me 11.20%.

I would imagine the Crescent Reach ZEM is purposefully huge for newer players so there could be a 11% cap in place before ZEM.

I then tested West Freeport with the level 1 dwarf warrior as well to compare with the video I found from 2020 - I was getting 11.20% per kill again from level 2 mobs. After leveling up to level 2, I noticed I could then get 11.243% as a cap in both West Freeport and East Commonlands. I am not sure why the cap went up? I then went into North Ro and was getting 12.743% at level 2 killing level 12 mummy's, so ZEMs definitely play a factor.

I then decided to test this level 2 character in Crescent Reach to make sure he would get 15% as well, which he did.

**Quests**

I tested with Crushbone Belts and got 21.3% per turn in at level 1. Whether there is a cap or not is yet to be seen but we know that the mob cap is not the same as the Quest cap at the very least.

### Current EQEmu:

**Mobs**
Level 1 killing a level 13 Caiman in Oasis grants you to level 3 1/2.

**Quests**
Turning in a Crushbone Belt at level 1 gets you to level 2 instantly.

### Conclusion/TLDR

Live look to have a cap of about 11% + ZEM - but the 18.7% monk video seems to go against this unless the Mischief TLP server boosted all ZEMs.
Quests dont seem to adhere to this cap as a single Crushbone Belt turn in gave me 21.3% at level 1. A rule would still be wise to let server operators control it, even if off by default.

**Comment by Valorith** [comment]
Should the % xp cap/kill only affect normal XP or AA xp also? @scotty0100
