### ISSUE TITLE
[Luabind] Windows Int64 Not Supported

### ISSUE THREAD

**Issue by nytmyr** [EQEmu/Server#2605]
Multiple lua methods result in overload errors on Windows due to int64 not being supported in Luabind. Linux methods work correct.

Examples:
SetHate
HealDamage
SetHP

This can be fixed via 
https://github.com/EQEmu/Server/blob/324d48aa903fe02403e1893aa4c586fb8ccc272b/libs/luabind/luabind/detail/policy.hpp#L699

By adding 
LUABIND_NUMBER_CONVERTER(unsigned long long, number)
and 
LUABIND_NUMBER_CONVERTER(signed long long, integer)

**Comment by Kinglykrab** [comment]
https://github.com/EQEmu/Server/pull/2717
