### ISSUE TITLE
Rule: NPCBuffLevelRestrictions causes High level group spells to fail when low level npc targetted

### ISSUE THREAD

**Issue by fryguy503** [EQEmu/Server#2808]
Code Location: https://github.com/EQEmu/Server/blob/master/zone/spells.cpp#L3206-L3211

Error: With a bard or other non target dependent group beneficial spell will fail when the Rule NPCBuffLevelRestrictions is enabled and the target is below the restriction level.

Tested by commenting out that section and it is no longer blocked.

**Comment by noudess** [comment]
Looking at this now.

**Comment by noudess** [comment]
Think I found it - fixing.  Will PR as soon as I can test.

**Comment by noudess** [comment]
Should be solved by:

https://github.com/EQEmu/Server/pull/2809
