### ISSUE TITLE
Water does not break line of sight and aggro is not cleared when you exit the water

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#2854]
You should not be able to attack/cast on targets that are underwater if you are not and vice versa. Mobs should not "see" you until you've broken the water surface plane. Aggro should also be cleared as soon as you exit the water. I think this has been addressed in the past but nothing was ever merged as far as I recall.

**Comment by Kinglykrab** [comment]
I believe this is resolved by https://github.com/EQEmu/Server/pull/3408.
