### ISSUE TITLE
[Bug] Casting self buffs getting SPELL_TOO_POWERFUL failure

### ISSUE THREAD

**Issue by Natedog2012** [EQEmu/Server#2923]
If I am targeting a low level character when casting my self buff I get the error "SPELL_TOO_POWERFUL" for my intended target even though its a self-cast buff.

Spell target should always be self for this target-type so somewhere its getting whatever I'm targeting

Spell: Cloak of Discord 
Target was level 50~ish

**Comment by noudess** [comment]
I'll take a look and repair it tomorrow.  This is along the same vein as the targetted NPC issue that I closed out on my PR.

Sorry!

**Comment by Kinglykrab** [comment]
Resolved by #2931.
