### ISSUE TITLE
EVENT_DISCONNECT only sent on "hard" camps - normal camps are not detected.

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#3019]
I am not sure if this is as intended or not, but EVENT_DISCONNECTED  is not delivered to (non-GM) clients on a simple camp.  Thus , we can't detect normal camps in q quest file,

https://discord.com/channels/212663220849213441/1078035709937602611/1080534228921495594

https://discord.com/channels/212663220849213441/1078035709937602611/1080534035668930623

https://discord.com/channels/212663220849213441/1078035709937602611/1080508362124427294

**Comment by Kinglykrab** [comment]
https://github.com/EQEmu/Server/pull/3153
