### ISSUE TITLE
Zones crashes on 29 Apr Release Binaries

### ISSUE THREAD

**Issue by Isaaru** [EQEmu/Server#3360]
We are getting some zone crashes on the new binaries related to the character_pet_buffs table. Value out of range for caster_level (usually something high like 90+) and the only way to fix the crash is to delete the offending line. This has effected every class we've played from warriors and paladins (no pets) to magicians. The buffs are not cast by us nor are they spells we would cast as buffs on pets. It happens during the zoning process, injects a bunch of data into the pet buffs table, then crashes the zone. The zone will continue to crash until the buffs are deleted from the db. It seems to be random when/why it happens but it's happening often enough that it's not truly random.

![Capture](https://github.com/EQEmu/Server/assets/19696544/a6baa7fd-4789-489b-88b0-e62ce877436b)

[log.txt](https://github.com/EQEmu/Server/files/11500811/log.txt)

**Comment by joligario** [comment]
In the logs, looks like the caster level was not high - 55

**Comment by joligario** [comment]
Looks like your example is specific to spell 5000. Assuming PEQ database, that is Righteous Assault. If you aren't casting the buff, perhaps it is a worn effect. That would explain an invalid caster level.

**Comment by Isaaru** [comment]
It's not a worn or proc effect either (it's happened on numerous characters, many of which are completely naked).

![image](https://github.com/EQEmu/Server/assets/19696544/3ab297e5-c48d-45e8-b581-ba3e4c809ca1)

**Comment by Isaaru** [comment]
![image](https://github.com/EQEmu/Server/assets/19696544/44edc518-a2fe-4ec0-babe-4f4a867e7609)

All the same except the first spell. Character is a naked level 60 paladin in this one.

**Comment by Isaaru** [comment]
More updates and new findings. Brought @Valorith into it for more fun.

We both logged in Mages with pets, both instantly crashed on login.

We both logged in Necros without pets, no issues.
- I summoned a pet and hit camp, instantly crashed
- Val summoned a pet and typed #gm off, instantly crashed

In all these crashes NO buffs were put into the character_pet_buffs table.

**Comment by Isaaru** [comment]
Pretty much confirmed it had to be a sql update that didn't process accurately. Completely fresh server but with current db still had issues. Reverted binaries to pre-4/29 and still had the issue. Reverted db to pre-4/29 and we're good now.
