### ISSUE TITLE
Replace abs, abs64, ABS, fabs, etc with std::abs

### ISSUE THREAD

**Issue by mackal** [EQEmu/Server#338]
We should now be using compilers that have all the correct C++11 overloads for these functions. Most of the 'cheap abs' macros will probably not actually matter with optimizations enabled.

Benefit? No silent narrowing or silly macros.

**Comment by Kinglykrab** [comment]
Resolved by https://github.com/EQEmu/Server/pull/2739 unless there's more I don't see.
