### ISSUE TITLE
No Access to Zone-Specific QGlobals

### ISSUE THREAD

**Issue by joligario** [EQEmu/Server#339]
In references to qglobals, I will use CHAR, NPC, ZONE.

When the qglobal cache is loaded, the zone-specific qglobals (for example: ANY, ANY, tutorialb) are not accessible. During troubleshooting, I noted that if we don't load the qglobals by global context (ANY, ANY, ANY), the zone globals load fine. Therefore, I assume that since global context qglobals are specifically tied to zone, perhaps they are overwriting the zone globals.

To test, I used both perl quests as well as #globalview command. Using PEQ database to test these zones, I used: tutorialb (amote/bmote), nadox(several emotes), guildhall (gports), etc.

**Comment by thalic** [comment]
This Issue is still valid. It is the reason why many Quests like all Nexus Portals to Luclin not working. Any solution for it?

**Comment by Akkadius** [comment]
The solution to fix this in Perl is to make sure that you have the table `perl_event_export_settings` and the appropriate sub events turned on that you want to be able to have access to qglobals.

The reason why they are turned off by default is that they are a high cost to constantly export for those subroutines when often they are not referenced.

Also see: http://www.eqemulator.org/forums/showthread.php?t=40147
