### ISSUE TITLE
Aggro mobs will disappear in to the "ground" and warp to the player when pulling up and down ramps, stairs or other uneven terrain

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#3450]
Plane of Sky - Azarack island is easily repeatable. Try kiting the Azaracks around the island. When you get far enough away or get out of their line of site they will often disappear in to the ground and pop up once the player has stopped moving. It's not like they are stuck and warp, it's like they are pathing under the ground and then popping up at the player location?
![5331e660656d4acc9a31e2683dd05ee6](https://github.com/EQEmu/Server/assets/84471005/26a23cd6-f947-4896-9323-e89bf3793a86)

**Comment by MidnightMusicClub** [comment]
This happens in most zones I've tested. Flat areas seem ok and ramps/stairs seem ok as long as line of sight isn't broken or you don't get too far ahead of the mobs. This started happening with the z-axis changes made to help with pathing in ToV and other zones.

**Comment by Akkadius** [comment]
There is a bad mesh here, pushed a new mesh for airplane https://github.com/Akkadius/eqemu-maps/commit/9ddf17741f843b9134e27f617b48ab3fc0be0a8e

**Comment by Akkadius** [comment]
Should be addressed by https://github.com/EQEmu/Server/pull/3502
