### ISSUE TITLE
NPCs using AI_SetRoambox for random pathing are getting stuck in trees, rocks and other objects and not able to path out of them

### ISSUE THREAD

**Issue by MidnightMusicClub** [EQEmu/Server#3451]
There are fewer issues with them getting stuck under the zone geometry now but they aren't able to maneuver around trees, rocks and other objects. https://i.gyazo.com/07a33baa9e699af8dab6bc6c7ecc0d5e.gif

**Comment by Akkadius** [comment]
Should be addressed by https://github.com/EQEmu/Server/pull/3502
