### ISSUE TITLE
[Bots] targetgroup and namesgroup actionables don't work in raids

### ISSUE THREAD

**Issue by titanium-forever** [EQEmu/Server#3567]
When a raid has been started, the bot actionables targetgroup and namesgroup cease to work. 

**Steps to reproduce:** 
- Spawn some bots and invite them to a group
- Target a bot in the group and summon it by namesgroup and targetgroup - should succeed (annotations 1 & 2)
- Spawn another bot and invite to a raid
- Target the same bot as before and summon it by namesgroup and targetgroup - will fail (annotations 3 & 4)
- Error messages: 
 - "You have no spawned bots meeting this criteria - type: 'targetgroup', name: ''
 - "You have no spawned bots meeting this criteria - type: 'namesgroup', name: '<botname>'
 - 
![GroupOnly](https://github.com/EQEmu/Server/assets/95503076/61cc9a7c-e4f1-4046-ae41-36fb6fc520a3)

![InRaid](https://github.com/EQEmu/Server/assets/95503076/f3f2081b-c1dc-4e07-ba7a-d24f356cd43f)

**Comment by Kinglykrab** [comment]
@Aeadoin @neckkola, should we make a `targetraid` and `namesraid` for this purpose?

This is due to the current code only checking for groups since it was written pre-raid functionality.
