### ISSUE TITLE
Mobs drop aggro after 10minutes of combat and re-trigger event_combat(e) methods in scripts

### ISSUE THREAD

**Issue by Ewiclip** [EQEmu/Server#3625]
There's a combat timer for aggro on NPCs that is exactly 10minutes. I can go punch a mob for 9:59 but if I stop punching them before 10;00 they will drop aggro off me and walk away. For regular group mobs this isn't an issue but for raid mobs that take longer than 10minutes to kill this will instantly drop the tank off aggro AND it will re-trigger event_combat() methods in that raid event. 

In the instance I tested there was an HP Event  set on combat that would spawn mobs. So at the 10minute mark the  event started spawning adds meant for 90% HP. 

It seems like this is not intended and perhaps a source code fix could be applied to prevent this from happening on raids. (This is easily reproducible but it does take 10minutes each time)

**Comment by fryguy503** [comment]
No where in the code have I seen any 10 minute timers, the checks each time the hatelist is updated. I know I have never seen this crop up and I have many events that are longer than 10 minutes and a few that would reset the whole event if the hate list was completely dropped.

We would need more logs to show this and duplicate it.

HateList Code: https://github.com/EQEmu/Server/blob/16ab1839e887cbe1c63c4452b5e29d1ffb4ad149/zone/hate_list.cpp#L817

**Comment by Ewiclip** [comment]
> No where in the code have I seen any 10 minute timers, the checks each time the hatelist is updated. I know I have never seen this crop up and I have many events that are longer than 10 minutes and a few that would reset the whole event if the hate list was completely dropped.
> 
> We would need more logs to show this and duplicate it.
> 
> HateList Code:
> 
> https://github.com/EQEmu/Server/blob/16ab1839e887cbe1c63c4452b5e29d1ffb4ad149/zone/hate_list.cpp#L817

Go punch a mob and then turn away from it for 10minutes. At the 10minute mark it will drop aggro and walk away.,

**Comment by fryguy503** [comment]
Sounds good, will try it and report back

**Comment by fryguy503** [comment]
If you are not interacting with the mob that is currently intended per the source and live.

https://github.com/EQEmu/Server/blob/16ab1839e887cbe1c63c4452b5e29d1ffb4ad149/zone/mob_ai.cpp#L1048-L1051

Sure someone could add a rule to prevent this, but it is also a method to prevent un-needed stale entries on a npc's hatelist.

**Comment by fryguy503** [comment]
With that said, I tested this on my server and didn't encounter the issue. 

![image](https://github.com/EQEmu/Server/assets/5864295/2edce439-a311-4ac1-bcad-4d6819be0d8e)

**Comment by Ewiclip** [comment]
Doing some more testing so I can give you more information on exactly how/where it happens.

**Comment by Kinglykrab** [comment]
Any follow up on this @Ewiclip?

**Comment by Ewiclip** [comment]
> Any follow up on this @Ewiclip?

  Yeah sorry got busy. I;m about to reproduce it but it's not consistent. I setup a macro that plucked an arrow at a mob once every 5minutes and went AFK for the night. Then I added an eq.debug into the combat event and noticed that twice over the night it went off again. 

As an experiment I did the same but with 10 different characters at the same time and I staggered their original engage time. Again I went AFK over night with each character re-engaging. This time I had significantly more message indicating that I had just engaged for the first time.

**Comment by Kinglykrab** [comment]
Any updates on this? I have not seen this on any servers that I have played on.

**Comment by Kinglykrab** [comment]
@Ewiclip

**Comment by joligario** [comment]
No response. Can re-open if needed.
