### ISSUE TITLE
Finishing Blow is adding spellbonuses twice

### ISSUE THREAD

**Issue by Osirous** [EQEmu/Server#3636]
Line 5216 of the attack.cpp has finishingblow adding the spellbonus twice instead of what im guessing should be itembonuses.
<img width="822" alt="attackcppFBwrong" src="https://github.com/EQEmu/Server/assets/5282643/ae903b59-5ce5-4dfb-8a4a-3c3150d11f7e">
If this is intentional please ignore. If its not, I am guessing its supposed to be itembonuses.

**Comment by Kinglykrab** [comment]
The first part is the finishing blow health ratio limit.
```cpp
auto fb_hp_limit = std::max(
	{
		aabonuses.FinishingBlowLvl[SBIndex::FINISHING_BLOW_LEVEL_HP_RATIO],
		spellbonuses.FinishingBlowLvl[SBIndex::FINISHING_BLOW_LEVEL_HP_RATIO],
		itembonuses.FinishingBlowLvl[SBIndex::FINISHING_BLOW_LEVEL_HP_RATIO]
	}
);
```

The second part is the finishing blow maximum level limit.
```cpp
uint32 FB_Level = 0;
FB_Level = aabonuses.FinishingBlowLvl[SBIndex::FINISHING_EFFECT_LEVEL_MAX];
if (FB_Level < spellbonuses.FinishingBlowLvl[SBIndex::FINISHING_EFFECT_LEVEL_MAX])
	FB_Level = spellbonuses.FinishingBlowLvl[SBIndex::FINISHING_EFFECT_LEVEL_MAX];
else if (FB_Level < itembonuses.FinishingBlowLvl[SBIndex::FINISHING_EFFECT_LEVEL_MAX])
	FB_Level = itembonuses.FinishingBlowLvl[SBIndex::FINISHING_EFFECT_LEVEL_MAX];
```

**Comment by Osirous** [comment]
So in the picture i was just showing that for level hp ratio you have aa spell and item, for damage you have aa spell and item, for max level you have aa spell and item, but for proc chance you have aa spell and spell. instead of aa spell and item.

**Comment by Kinglykrab** [comment]
My apologies. I didn't even see the boxes to the side there. Should definitely be `itembonuses` there instead of `spellbonuses` twice.

**Comment by Kinglykrab** [comment]
My pull request should resolve this. Good eye, mine definitely aren't. :+1:
