### ISSUE TITLE
Discrepancies in time

### ISSUE THREAD

**Issue by joligario** [EQEmu/Server#3700]
When setting time using `#time` or `#set time`, the time in game looks right, but the message is wrong.
![image](https://github.com/EQEmu/Server/assets/3617814/4c853d50-7a58-46bc-856f-96aa355a05fe)

Then, through quest, `$zonehour` is yet another our different.
![image](https://github.com/EQEmu/Server/assets/3617814/1d6840d1-e142-4f63-828f-738386ff161b)

Also noticed in `gm_commands\set\time.cpp` it is using `Strings::ZoneTime(zone->zone_time.getEQTimeZoneHr(), zone->zone_time.getEQTimeZoneHr())` in 3 locations
That last element should be `zone->zone_time.getEQTimeZoneMin())`

**Comment by Akkadius** [comment]
Is this new?

**Comment by joligario** [comment]
I remember someone else mentioning an in-game time issue long ago, but can’t remember the details. Son can’t say for certain this is new.

**Comment by regneq** [comment]
hmm   I test this in local takp server
![image](https://github.com/EQEmu/Server/assets/3778417/d0086ab6-112a-437d-a7d2-5b320afa6a6f)

It's using the old #time command

**Comment by regneq** [comment]
Seems like on EQEmu, it set the time a hour early but the message have it a hour ahead.

**Comment by nytmyr** [comment]
> Is this new? (Is this a regression?)

It has been like this for a long while. When I did my day/night script I had to factor the hours in like mentioned

**Comment by fryguy503** [comment]
Same here on factoring in the difference on my scripts.
