### ISSUE TITLE
Fix for GroupLeaderName() returning wrong group leader. 

### ISSUE THREAD

**Issue by Bastion-Server** [EQEmu/Server#3706]
Writing this up as a bug because I can't seem to be able to do this as a Pull Request. When the Groups leader has changed, the function that returns the leader name only ever returns membername[0]'s name, not the actual leader if the leader is changed in group. This nerfs the packet and the clients reject it on notify. Using the information noted in expeditions concerning the need to force a database update, I made the following changes to fix the bug.

This is the function in groups.h:
> const char*	GetLeaderName() { return membername[0]; };

I changed it to:
> const char*     GetLeaderName() { return GetGroupLeaderName(GetID()).c_str(); };

Then added  the following to private:    

> std::string     GetGroupLeaderName(uint32_t group_id);

And appended the below to groups.cpp:
   
>     std::string Group::GetGroupLeaderName(uint32_t group_id) {
>                 char leader_name_buffer[64] = { 0 };
>                 database.GetGroupLeadershipInfo(group_id, leader_name_buffer);
>                 return std::string(leader_name_buffer);
>     }

This resolved the issue and required no other changes to the underlying code.

-- Nameless

**Comment by joligario** [comment]
https://github.com/EQEmu/Server/issues/368

**Comment by Kinglykrab** [comment]
https://github.com/EQEmu/Server/pull/3712
