### ISSUE TITLE
zone_controller.pl EVENT_DEATH_ZONE sometimes not providing killed_entity_id

### ISSUE THREAD

**Issue by jdestefx** [EQEmu/Server#3721]
In the code below, if you #kill an npc instantly,  killed_entity_id will have the proper value.  If you aggro the mob first, then damage it down and kill it, then killed_entity_id will be zero all the time.

```
sub EVENT_DEATH_ZONE {
        quest::debug("killed_entity_id:".$killed_entity_id);
        quest::debug("killed_npc_id:".$killed_npc_id);

```
![image](https://github.com/EQEmu/Server/assets/10792512/081d8886-3a1d-4119-b3a3-f8bc2f48dff8)

![image](https://github.com/EQEmu/Server/assets/10792512/93ec5551-58f8-4bba-a3c0-335e03f1d979)

**Comment by Kinglykrab** [comment]
If NPCs are killed instantly they sometimes do not properly send their entity ID since the `killed` pointer used to get the entity ID may no longer be valid.
