### ISSUE TITLE
windows installer: Can't open new_server

### ISSUE THREAD

**Issue by martinlindhe** [EQEmu/Server#3741]
While running `eqemu_install.bat` on a Windows 10 machine, after some time this error appears

```
Can't open new_server: No such file or directory at eqemu_server.pl line 1314.
```

After that, the user is presented by a menu where you can type `new_server` and enter. If you do type `new_server` and enter you end up with a successful install. If you however follow the guide at https://docs.eqemu.io/server/installation/server-installation-windows/, you might think the installation was successful by now.

**Comment by Akkadius** [comment]
Strange, I'll take a look at it this week

**Comment by Akkadius** [comment]
I replaced the windows installer this week, give it a go https://docs.eqemu.io/server/installation/server-installation-windows/
