### ISSUE TITLE
Database starting_items Table Incorrect Mapping

### ISSUE THREAD

**Issue by brickbuckett** [EQEmu/Server#3764]
I'm sure this is known, but it looks like the starting items are not quite right. Classes are getting spells they can't use, or sometimes equipment they shouldn't be able to equip. The latter actually results in the user not being able to do damage until they equip something they can actually use.

Is there already someone working on this? I ask because I would like to contribute if there isn't someone doing it already. I really want to see the 'out of the box' experience for new server owners more streamlined. I checked the current pull requests and issues, and didn't see any mention of this.

Please let me know and I'll get started immediately!

**Example**

Barbarian Berserker
- Item: 1x Backpack
- Item: 20x Break Cakes
- Item: 20x Skin of Milk
- Spell: Minor Healing (Not useable by class)
- Spell: Courage (Not useable by class)
- Primary: Club (Not useable by class)
- Secondary: Gloomingdeep Lantern

**Comment by joligario** [comment]
After this update, please let us know if that fixes the majority. If there are still changes that need to be made, there are a few options. Submit an SQL fix here or on [PEQ](http://www.projecteq.net/forums/index.php) or a provide descriptive changes over on PEQ.

**Comment by brickbuckett** [comment]
starting_items table migrated successfully and looks good!
