### ISSUE TITLE
Recent database might be missing content_flags for Frostfell npcs (and more?)

### ISSUE THREAD

**Issue by jdestefx** [EQEmu/Server#4088]
Recent fresh install shows Santug Claugg active (for example in felwithea).  I could not find any justification for why he's active when he should be hidden behind some kind of event or content flag, however he doesn't have any content flags set in the DB.

**Comment by Akkadius** [comment]
PEQ database is under active heavy development with the expansions project. Soon he will be behind a content flag and content flag defaults will be distributed - for now new installs are not going to be perfect.
