### ISSUE TITLE
CMake Error at CMakeLists.txt

### ISSUE THREAD

**Issue by bullr** [EQEmu/Server#4175]
Pulling down clean sources and running the following commands results in 2 errors during the CMAKE process. This happens on the master branch as well as v22.46.1 and v22.47.0 I have not tried any other previous releases.

`cmake -DEQEMU_BUILD_LOGIN=ON -DEQEMU_BUILD_LUA=ON -G "Unix Makefiles" ../server_source/`

```
CMake Error at CMakeLists.txt:439 (ADD_SUBDIRECTORY):
  The source directory

    /home/eqemu/server_source/submodules/fmt

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:440 (ADD_SUBDIRECTORY):
  The source directory

    /home/eqemu/server_source/submodules/libuv

  does not contain a CMakeLists.txt file.

```

and

```
CMake Error at CMakeLists.txt:451 (ADD_SUBDIRECTORY):
  The source directory

    /home/eqemu/server_source/submodules/recastnavigation

  does not contain a CMakeLists.txt file.

```

**Comment by joligario** [comment]
My guess is you haven’t yet pulled the submodules.
git submodule init
git submodule sync
git submodule update

**Comment by bullr** [comment]
Your guess is correct! Thanks!
