### ISSUE TITLE
Sense Heading does not trigger EVENT_USE_SKILL

### ISSUE THREAD

**Issue by jdestefx** [EQEmu/Server#4250]
Would like to use this skill for a quest, but doesn't look like it's captured.  Other skills I can get to spit out some debug info, but not this one.

If possible, make sure this can be captured by global_player, too.

**Comment by Kinglykrab** [comment]
As you can see in this code, we ignore `OP_SenseHeading` if that rule is set to `false`, meaning we never call `Handle_OP_SenseHeading`.

![image](https://github.com/user-attachments/assets/692fac28-8c11-4cef-a234-42d3e58addd1)

**Comment by Kinglykrab** [comment]
I added https://github.com/EQEmu/Server/pull/4424 so that you do not have to set the rule to `true` in order for Sense Heading to use `EVENT_USE_SKILL` anymore, as it should parse regardless of the rule's status.
