### ISSUE TITLE
New Taunt has multiple messages on success.

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#4257]
On success:

[Mon Apr 15 09:36:10 2024] Auto attack is on.
[Mon Apr 15 09:36:10 2024] You try to crush a giant skeleton, but miss!
[Mon Apr 15 09:36:10 2024] You crush a giant skeleton for 18 points of damage.
[Mon Apr 15 09:36:10 2024] You bash a giant skeleton for 32 points of damage.
[Mon Apr 15 09:36:10 2024] You taunt a giant skeleton to ignore others and attack you!
[Mon Apr 15 09:36:11 2024] You taunt a giant skeleton to ignore others and attack you!

On failure:

[Mon Apr 15 09:36:28 2024] You taunt a giant skeleton to ignore others and attack you!
[Mon Apr 15 09:36:28 2024] You have failed to taunt your target.

The old system did not give you the same message twice on success.  It did sometimes trigger the mob to speak up.

Do we want that back?

**Comment by fryguy503** [comment]
Are we passing the message to the client or is it client controlled? I see the successful taunt mob message `I'll teach you to interfere with me %3.` if the target can speak, and the failed message. But not seeing the `You taunt %s to ignore others and attack you!`

**Comment by fryguy503** [comment]
Oh I see, I was looking at the wrong branch - TAUNT_SUCCESS - Guessing the client is generating its own and we do not need to send it (My branch didn't have that call)

**Comment by fryguy503** [comment]
https://github.com/EQEmu/Server/pull/4258

**Comment by Kinglykrab** [comment]
Resolved by #4258.
