### ISSUE TITLE
2. The ROF2 client connects to the latest eqemu server. When you right-click on the rof2 game interface for a long time, the game crashes directly!

### ISSUE THREAD

**Issue by infoall** [EQEmu/Server#4283]
1. Please tell me how to solve the problem that Chinese NPC names display garbled characters on the client!
2. The ROF2 client connects to the latest eqemu server. When you right-click on the rof2 game interface for a long time, the game crashes directly!
Can any master please help me solve this problem? Many thanks!

1，请问如何解决中文NPC名字后，在客户端显示乱码！
2，ROF2客户端连接最新的eqemu服务器，右rof2游戏界面长时间右击的时候，游戏直接崩溃！
请问哪位大师能帮忙解决一下吗？万分感谢！

**Comment by Kinglykrab** [comment]
1. Unfortunately I don't think the Client properly supports Chinese characters.
2. Not sure what you mean by, "When you right-click on the rof2 game interface for a long time, the game crashes directyl!", could I get more information here?

**Comment by infoall** [comment]
能帮忙修复这个游戏完全支持中文吗？比如：聊天窗口输入中文，NCP中文名，以及全中文的任务！
Can you help fix this game to fully support Chinese? For example: input Chinese in the chat window, NCP Chinese name, and all Chinese tasks! 
Thanks very much!

**Comment by Kinglykrab** [comment]
Unfortunately I cannot help you with this issue.
