### ISSUE TITLE
de-leveling with #setlevel doesn't remove skills you shouldn't have

### ISSUE THREAD

**Issue by jdestefx** [EQEmu/Server#4300]
For example, if you level up to level 50 and max your skills, you will have the skill "Double Attack",  but if you then #setlevel back down to level 5, then #set skill_all 1, then  #set skill_all_max (to get your skill caps back where they should be),  it will APPEAR as though you DON'T have "Double Attack" anymore, but if you go attack some mobs, you WILL double-attack - and the skill will be listed in character_skills.

FWIW I came up with this query to drop skills I shouldn't have:

7 = my char ID
3 = paladin (my char)

delete from character_skills where id=7 and character_skills.skill_id in (select skill_id from skill_caps where class_id = 3 and level = 5 and cap=0);

After running that, I logged out and back in (not sure if this was necessary?) and it appears to have solved the issue.

**Comment by jdestefx** [comment]
Another observation:  
#level 50
#set skill_all_max 
#level 5
#set skill_all 0

select * from character_skills where id = {yourCharID}    --->  will show multiple skills that are still max value.

**Comment by Kinglykrab** [comment]
Fixed by https://github.com/EQEmu/Server/pull/4423.
