### ISSUE TITLE
devtools toggle link doesnt bring the devtool window back

### ISSUE THREAD

**Issue by jdestefx** [EQEmu/Server#4307]
if you snooze the devtools window, you can't bring it back unless you zone.  there is a toggle in the #devtools command, but it doesn't seem to do anything.

if toggle is meant to be a larger on/off, maybe cycling it could also reset the snooze?  or maybe add a snooze on|off link in the #devtools options.

**Comment by Kinglykrab** [comment]
Resolved by https://github.com/EQEmu/Server/pull/4425.
