### ISSUE TITLE
typing #modifynpcstat with no params will crash your server

### ISSUE THREAD

**Issue by jdestefx** [EQEmu/Server#4404]
typing #modifynpcstat with no params will crash your server

**Comment by Kinglykrab** [comment]
Not seeing this at all using multiple different combinations of this command, closing until we get proof of this bug or steps to reproduce.

**Comment by jdestefx** [comment]
Sounds good. I suppose it's possible I had gotten corrupted somehow.  I'll try again tonight and confirm.

**Comment by jdestefx** [comment]
Recreated this.   Add a single space after the command and it should trigger a crash.

**Comment by jdestefx** [comment]
![image](https://github.com/user-attachments/assets/41b9b287-a3f4-478e-a0c4-3099523a82d7)

**Comment by jdestefx** [comment]
![image](https://github.com/user-attachments/assets/45315e1f-96f0-42e3-be19-6b568cbd8e89)
