### ISSUE TITLE
using quest::echo(15, "test");  inside EVENT_TIMER causes a crash

### ISSUE THREAD

**Issue by jdestefx** [EQEmu/Server#4430]
Was working on a quest and discovered this code kept crashing me.

`

	sub EVENT_ITEM {
		if (plugin::check_handin(\%itemcount, 182402=>1, 182405=>1, 182408=>1, 182411=>1)) {
			$client->Message(15, "You find the correct places in the skeleton for all of the missing bones.  As you place the last one, the skeleton begins to vibrate. A sense of danger begins to take hold, and you immediately suspect something bad is about to happen.");
			quest::settimer("popBoss", 5);
			return(0);
		}
		
		plugin::returnUnusedItems(\%itemcount);
	}

	sub EVENT_TIMER {
		if ($timer eq "popBoss") {
			quest::echo(15, "test");
			# $npc->Depop();
			# quest::ze(15, "Test");
			quest::stoptimer("popBoss");
		}
	}
`

**Comment by Natedog2012** [comment]
Seems the initiator is NULL during EVENT_TIMER
![Screenshot_12](https://github.com/user-attachments/assets/b11d4b9b-ef31-4a66-8829-3cc517b6d083)

**Comment by jdestefx** [comment]
I was able to work around it, really just letting you guys know so u can
add some protection.  I don't NEED quest::echo to work if it would be a
headache to fix.  I kinda realized there's some unpredictability inside
EVENT_TIMER, like how $client doesn't exist either due to the nature of the
function.

**Comment by Kinglykrab** [comment]
I will fix this when I’m back at my PC.

**Comment by Kinglykrab** [comment]
https://github.com/EQEmu/Server/pull/4433
