### ISSUE TITLE
#help faction #set faction #setfaction not doing anything

### ISSUE THREAD

**Issue by jdestefx** [EQEmu/Server#4440]
"#help faction" shows some commands regarding setting factions, but the commands don't do anything and just keep showing the full list of #set options.

**Comment by joligario** [comment]
This command was removed in https://github.com/EQEmu/Server/pull/3577/files in favor of `#npcedit faction`. Not sure why the sub-command is not being purged on delete.
cc: @noudess @Kinglykrab

**Comment by Kinglykrab** [comment]
Resolved by https://github.com/EQEmu/Server/pull/4448.
