### ISSUE TITLE
$inv->DeleteItem(<itemid>,<qty>);  not honoring <qty>

### ISSUE THREAD

**Issue by jdestefx** [EQEmu/Server#4450]
I had a stack of 5 "keys", and used that method to attempt to remove one of the keys, reducing the stack to 4, and it does nothing.  The stack remains at 5.

$inv = $client->GetInventory();
$inv->DeleteItem(nnnn, 1);

So,  I switched to $client->RemoveItem(nnnn, 1), and that method works as expected.

**Comment by joligario** [comment]
Did you check quest errors? Looking at the code, it is named `DeleteItemInInventory`
```
	package.add("DeleteItemInInventory", (void(*)(Client*, int16))&Perl_Client_DeleteItemInInventory);
	package.add("DeleteItemInInventory", (void(*)(Client*, int16, int16))&Perl_Client_DeleteItemInInventory);
	package.add("DeleteItemInInventory", (void(*)(Client*, int16, int16, bool))&Perl_Client_DeleteItemInInventory);
```

**Comment by joligario** [comment]
Looks like it is looking for slot, not item id

**Comment by jdestefx** [comment]
No errors when I use $inv->DeleteItem(nnnn,1);

I'm a couple builds behind - but spire shows it as I use it:

![image](https://github.com/user-attachments/assets/4815feab-6d1f-471e-a1e2-0f50bc2c5538)

**Comment by jdestefx** [comment]
Oh crap you're right (about slot_id)... my bad.

**Comment by joligario** [comment]
My initial was looking at client vice inventory. That's why I redid my response.

**Comment by jdestefx** [comment]
Misread the docs...   $inv->DeleteItem wants slot_id, not an itemID.  Closing this.
