### ISSUE TITLE
GM override message appearing when unnecessary

### ISSUE THREAD

**Issue by jdestefx** [EQEmu/Server#4568]
I get this GM message any time I do a #cast or proc a weapon.  Doesn't matter if the spell is "Restricted" or not.  It always appears.

![image](https://github.com/user-attachments/assets/63178d45-c941-41ca-a4cf-467dec957da7)

![image](https://github.com/user-attachments/assets/7cb468f4-a6d5-4dd8-9aef-0e32236229c0)

**Comment by Kinglykrab** [comment]
Resolved by https://github.com/EQEmu/Server/pull/4571.
