### ISSUE TITLE
Merc Buffs

### ISSUE THREAD

**Issue by mackal** [EQEmu/Server#466]
You can not click off the buffs on your merc, you should be able to.

**Comment by Kinglykrab** [comment]
![image](https://user-images.githubusercontent.com/89047260/212581295-8343aff1-c7d8-4eea-8b9a-590718be6fed.png)
![image](https://user-images.githubusercontent.com/89047260/212581303-2200fe2b-924a-4593-b9a6-10850eaaf1cb.png)
![image](https://user-images.githubusercontent.com/89047260/212581307-dfafdc51-e6f4-443a-8289-f70bf6c6ab09.png)
Works as of January 15th, 2023, not sure when it was fixed.
