### ISSUE TITLE
Shared Memory without shared folder (minor bug)

### ISSUE THREAD

**Issue by Xackery** [EQEmu/Server#492]
`[Status] Loading items...
[Error] EQEmu Exception (Shared Memory) in /var/eqemu/latest/common/memory_mapped_file.cpp at line (89): Could not open a file for this shared memory segment.`

Just a note that this error pops up quite cryptically if you run ./shared_memory without a shared directory.

**Comment by Uleat** [comment]
The windows install guide specifies that this directory be created: http://wiki.eqemulator.org/p?Complete_Windows-based_Server_Setup_Guide&frm=Main#step-1-setting-up-a-folder-structure

There is also a vague linux reference found here: https://github.com/EQEmu/Server/wiki/Linux-server-setup

**Comment by mackal** [comment]
Doing this stuff cross platform isn't exactly pretty. Maybe doing it with boost.filesystem would be a good idea (which was accepted into C++17)

**Comment by Akkadius** [comment]
This is implemented per:

https://github.com/EQEmu/Server/commit/34ffb5b90827cf907c90e4a84b0c158a3f9ff847

http://i.imgur.com/Q8gUmb3.png
