### ISSUE TITLE
maps isn't honored in eqemu_config.xml

### ISSUE THREAD

**Issue by Xackery** [EQEmu/Server#495]
This isn't really a bug, and it's really minor, but figured i'd share anyways.

I try to keep all my folders lowercase on my linux box (case sensitive) and made a maps folder. I edited the <maps>maps</maps> entry in eqemu_config to reflect this, however when I started the server up, it was still noting that "./Maps/zonename.map could not be found", and found the solution was simply set the cmake config flag to update the proper case sensitive maps directory.

So, it seems eqemu_config is not being honored for path search, there's a #define used in the source for the map directory, and it is set based on cmake.

**Comment by chris-statzer** [comment]
So how do people want this handled? Remove the item in the default config.xml or fix it to be respected by the server and use the Cmake var if its not defined in the xml?

**Comment by Xackery** [comment]
Good question. I prefer XML personally (eqemuconfig), since it's the easiest to on the fly edit for different environments. Not every binary is built from source for each environment so cmake isn't always ideal.

**Comment by Akkadius** [comment]
This should be fixed in new logic. I will be testing in Linux here shortly.

https://github.com/EQEmu/Server/commit/e7e379c71b39f991b467aab26ee6f1da4e6db6e8

http://i.imgur.com/QjPsnxX.png
