### ISSUE TITLE
Faction Cap Issue

### ISSUE THREAD

**Issue by AsmoTiC** [EQEmu/Server#513]
Having trouble with faction capping to early for race/class combos with negative modifiers.  I have a detailed write-up of the problem here [http://www.eqemulator.org/forums/showthread.php?t=40511](url).

Issue #358 back in Feb. 2015 looked like it was supposed to fix this.  I double checked that the current Git Repo has these changes, as well as the code i'm compiling from.  Here is a link to the issue to make things easy - [https://github.com/EQEmu/Server/commit/115d0d14ac462ef1725d4f9e66f169646ec2a3e5](url)

Made a clean clone of the Repo on 03-28-2016, made a new cmake, and clean compile.  Tested everything by lowering an Orge Warrior from 1450 Claws of Veeshan faction to 1449 in the DB.  Logging out and back in.  Killing an NPC worth 15 CoV faction, checking the DB to see he's back to 1450.  Tried to kill another NPC, receiving the message about the faction can't possibly get any better.

1450 leaves the Orge Warrior (Agnostic) as Warmly with CoV.  If he was an Ogre Warrior (Rallos Zek) the problem would be even worse.

**Comment by AsmoTiC** [comment]
Perhaps the math could work better if it was changed to something like this.  Forgive the roughness, and lack of correct variables, it's just to pass on the idea.

Faction_Modified = Base + Race + Class + Deity
Character_Faction = DB_Faction_Earned + Faction_Modified
Adjust DB_Faction_Earned to be >= -3000 and <= 1200 after taking into account Faction_Modified.

DB_Faction_Earned would be the value each character has stored in the DB.  Just seems like the faction modification from Base, Race, Class and Deity needs to be done against the amount of faction earned by the player.  Not thrown in as part of the overall value.

This will make someone with a -1000 Modified value, have more faction to earn, but still be able to cap the faction at 1200 like everyone else.

Just an idea, hopefully it comes across clearly.

**Comment by noudess** [comment]
I'll dig into this and get back to you.  I want to improve what I put in place if there are discrepancies between what is being allowed on eqemu and what we all want to see happen.

**Comment by noudess** [comment]
Not fully back into this yet... but I wanted to say a couple of things.

A better breakdown of what I am about to comment on is here:  [http://wiki.eqemulator.org/p?Faction_Overview](url)

To understand any particular example, I'd need to know what some values are in the db you are using.

The number that dictates how many points can be earned/lost is the starting faction # for the faction itself, found in the faction tables.  Whatever this # is, it can be remedied through action by a player.   While a faction that starts everyone out at 0 allows a gain of 1200 and a loss of 3000, a faction that starts out at -1000 allows a gain of 2200 and a loss of only 2000.

That's the PC's core earn/loss range.

However, class, race and deity penalties are ALWAYS going to be applied.  So if a faction starts out -500, you can earn up to 1700 more to max you out at 1200.  But if the database has penalties for race/class/deity, those are still subtracted from the total.  So if you worship a deity with a -1000 penalty in the above case, the best you could ever be is base(-500) + max_earned_in_this_spot(1700) - deity penalty(-1000) = 200.

It has been my experience that many eqemu databases have what I consider to be some really wrong bonus/penalties for race/class/deity in them. 

For example, I see lots of things like -750 for certain deities, but when I research live, by taking a brand new human/bard of that deity and do a con, I get apprehensive, which is clearly not reflecting such a huge penalty.

I'd be happy to help you tweak your db to give you the results you want.

**Comment by AsmoTiC** [comment]
I'm using a pretty bunch base PEQ DB.  08-2015 I believe the date was, whichever is listed in the wiki walkthrough.  Additionally, there is a pretty decent thread that spurred up on the PEQ forums.  Sounds like people are thinking the range on live is compressed.  [url]http://www.peqtgc.com/phpBB3/viewtopic.php?f=17&t=15758[/url] is the link to that thread.

As far as values.  Just looking at Claws of Veeshan, as an example:
id 42, Claws of Veeshan, base -250

Mod ID's for CoV:  (Note Effective Faction is just Base + Mod, so omitted here)
id 170, Race Troll, Mod -150
id 171, Race Ogre, Mod -150
id 172, Race Werewolf, Mod -1000
id 173, Race Wolf, Mod -250
id 174, Race Elemental, Mod -500
id 175, Race Eye of Zomm, Mod -250
id 176, Iksar Skeleton, Mod -1000
id 177, Race New Skeleton, Mod -1000
id 178, Deity Bertoxxulous, Mod -250
id 179, Deity Brell Serilis, Mod -50
id 180, Deity Cazic-Thule, Mod -250
id 181, Deity Karana, Mod -250
id 182, Deity Rallos Zek, Mod -500
id 183, Deity The Tribunal, Mod -50
id 184, Deity Veeshan, Mod +750

From my understanding, nobody really knows where those values came from.  They might have been reversed out of an old client, or something.  So there is a good chance they are part of the problem.

I will note that on live I took the time to test CoV with my Iksar Monk of Cazic Thule.  He is able to get Ally on live.  Not sure how deep in he is, once I got the message you can't gain anymore, I left to check West ToV and con mobs.  On Emu, he gets to kindly I think, and that's after receiving the "can't gain any more faction".  So he's at -500 mod on Emu.  So with the Personal Cap set at 1200, and the way the Emu math is done he caps at 700.  In the database, I want to say he reads as 1450.

Anyway, in the end.  I appreciate you taking a look at it.  I know there are a bunch of people that have problems with it, threads pop up on a semi-regularly basis in regards to faction capping to early, or not going low enough for others.  That thread I linked has some of the best discussion to date on the issue.

**Comment by noudess** [comment]
I am uploaded a pull request that changes the personal range to -2000/2000 as seems to be a consensus.

**Comment by AsmoTiC** [comment]
Agreed.  My bandaid fix for my server was to increase the Personal Max.  It means some race/class/deity combo's can get really high into Ally, but it's a pretty reasonable compromise in the end.  So you can kill a couple West ToV dragons and still be Ally, not really a huge deal.  Not as big of a deal as someone not being able to complete a Halls of Testing quest because the server wouldn't allow them to hit Ally.

Feel free to close this Issue at anytime.  I'm pretty satisfied with the fix.  Thanks again for investigating the problem!

**Comment by noudess** [comment]
On live, does a kill of a West ToV dragon always knock you out of ally?  Do we know the hits?  I see Zam doesn't know many of the hits, but the ones I see are like 100, 500...  500 would knock off the extra 800 pretty quickly.  Does one kill knock you out of ally on live?  One possibility is that some factions can have bigger faction ranges than others.  That would be a big change.

**Comment by AsmoTiC** [comment]
I'll take a look at those West ToV hits.  Going to take just a bit to get the test done.  I had run some tests against North ToV mobs to see faction hits since the PEQ DB doesn't have most of the mobs up there giving hits, and some mobs on the wrong faction all together.  So my Monk isn't Max ally at the moment.  I'll need to perform another ethnic cleansing of Kael to max again.  Once I do that, i'll try and pop a named in West ToV and let you know what kind of hit those dragons give.

Will try and get max Ally and a kill in by next weekend (June 18th, 19th of 2016), and report back here.

**Comment by AthrogatePEQ** [comment]
I'm pretty sure that if you were max ally and killed 1 Dragon it knocked
you close to 1 point out of the reach of doing the quests.  On EQMac, being
max ally, one raid would take me a week of grinding in the Kael Arena to
have my faction back to do the armor and Halls of Testing Quests.  Once the
guild I raided with on EQMac started raiding NTov and WToV regularly I gave
up trying to fix it because the faction hits were really big.

**Comment by AsmoTiC** [comment]
Just a quick follow up.  Took the Monk (Iksar of Cazic-Thule) to Kael, and maxed his CoV again (Your faction standing with Claws of Veeshan could not possibly get any better.).

Ran back to Tov, entry mobs and West ToV mobs all con "... regards you as an ally ...".  Unfortunatly, no named were up, but killed some trash and tracked how much negative CoV it took to to be Ally anymore.  -10 rep per trash mob in WToV.  Took 11 mobs to drop into Warmly (-110 CoV Rep).

Hopefully this helps a little.  Don't have another character max ally, or i'd try them too.  At some point I might grind my bard up, she shouldn't have any negative as she's agnostic.  Would be interesting to see if she goes from Max ally to Warmly in 11 kills as well.  Future test sometime when I have an afternoon to lay waste to Kael

**Comment by mackal** [comment]
Fixing the ranges for each faction level (we are wrong) has many complications that are not easy to resolve. (to put it simply, the number of issues it would cause would be greater than 1000)

**Comment by noudess** [comment]
This good for now (close issue) or do we want to consider wider scoping changes?  I'm ok with it as/is but I can see there is plenty of room for improvement.

**Comment by AsmoTiC** [comment]
I'm pretty satisfied with the current fix.  It's not perfect, but certainly the easier way to go while still solving the problems with certain combinations not being able to cap.

I think it's safe to close the issue at this point.
