### ISSUE TITLE
create event_loot_start function

### ISSUE THREAD

**Issue by cream24** [EQEmu/Server#523]
this function allows you to check globals, etc when attempting to loot an item, but prior to the item being looted - similar to lore check.  this is necessary to enforce epic 1.5, epic 2.0 progression and prohibit looting if a player is not on the required step.

**Comment by Akkadius** [comment]
Did anyone look into getting this working?

**Comment by mackal** [comment]
The issue we wanted to solve was solved, but this specific scripting wasn't implemented.

**Comment by Akkadius** [comment]
Do we need this issue open then
