### ISSUE TITLE
create enhanced find_path function

### ISSUE THREAD

**Issue by cream24** [EQEmu/Server#524]
a function with allows you to use the findpath function (create yellow path from client to npc in town) in quest files.   this would be used in warr 1.5, mage 1.5 among other appications
e.x
findpath ( fromClient,  toX, toY, toZ);
findpath ( fromClient,  toMob) ;

it should handle a situation where a target mob is roaming and recalc the path

**Comment by Akkadius** [comment]
We could make something like this but it wouldn't be friendly on a map with a lot of things in between point A and point B.

@KimLS was working on generating all of the path files but I've not heard an update regarding this

**Comment by Kinglykrab** [comment]
Resolved by https://github.com/EQEmu/Server/pull/2740.
