### ISSUE TITLE
Acumen stacking with itself

### ISSUE THREAD

**Issue by N0ctrnl** [EQEmu/Server#538]
You can fill up the buff window with just Acumen if so inclined.
![acumen](https://cloud.githubusercontent.com/assets/1110540/17176740/b2964eb8-53d3-11e6-8a56-c9efbf25f58c.jpg)

The spell is the stock Acumen spell from the PEQ database - ID 2248

**Comment by SecretsOTheP** [comment]
Demonstar55 just simply needed more junk buffs for his dragon slaying.
Nothing to see here.
