### ISSUE TITLE
Slam not working for non-bash classes?

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#543]
The racial slam command does not seem to function for non bash classes.

From what I understand it should have a chance of stun and 1 HM of damage.

Creating a level 1 barbarian rogue - mashing slam seems to do nothing.

**Comment by mackal** [comment]
This probably broken we I made it so Bards with Furious Refrain wouldn't crash the sever ><

**Comment by Akkadius** [comment]
@mackal did you plan on adjusting this or maybe you did it already?

**Comment by emagi** [comment]
This capability was never supported, unfortunately my code is way off from yours at this point, but maybe this snippet can help (OPCombatAbility bash skill block).  This block is assuming the stun is successful, so any 'chance' to stun should be handled before this.


				bool stunTarget = false;
				
				switch(GetClass())
				{
				case SHADOWKNIGHT:
				case PALADIN:
					{
						const ItemInst *wpn = CastToClient()->GetInv().GetItem(SLOT_PRIMARY);
							if ( wpn && ( wpn->GetItem()->ID == 10099 || // Pally Epic
										wpn->GetItem()->ID == 14383 )  ) // SK Epic
								stunTarget = true;
						break;
					}
				}
					switch(GetBaseRace())
					{
					case BARBARIAN:
					case TROLL:
					case OGRE:
						{
							stunTarget = true;
							break;
						}
					default:
						{
							// Image (2014): this will allow non big races when they bash to stun if they have a shield
							if ( IsClient() && skill == BASH )
							{
								ItemInst* inst = CastToClient()->GetInv().GetItem(SLOT_SECONDARY);
								if ( ( inst != NULL && inst->GetItem()->AC > 0 ) || CastToClient()->GetAA(aa2HandBash) > 0 ) // Image: 5/28/2015, two handed bash (aa2HandBash) addition to stun fix for bash
									stunTarget = true;
							}
							break;
						}
					}

				
				if ( stunTarget )
				{
					// these guys can bash and stun
					if ( who->IsClient() )
						who->CastToClient()->Stun(MakeRandomInt(500,1000), true);
					else if ( who->IsNPC() && !who->CastToNPC()->SpecAttacks[UNSTUNABLE] )
					{
						who->CastToNPC()->Stun(MakeRandomInt(500,1000), true);
					}
				}

**Comment by emagi** [comment]
Accidentally deleted this reposting.  In any case OPCombatAbility has a bash skill section to handle this.  This assumes the chance to stun succeeded (also sorry but my code is prob way off from current eqemu, just gave this snippet as an idea of what needs to be done)

				bool stunTarget = false;
				
				switch(GetClass())
				{
				case SHADOWKNIGHT:
				case PALADIN:
					{
						const ItemInst *wpn = CastToClient()->GetInv().GetItem(SLOT_PRIMARY);
							if ( wpn && ( wpn->GetItem()->ID == 10099 || // Pally Epic
										wpn->GetItem()->ID == 14383 )  ) // SK Epic
								stunTarget = true;
						break;
					}
				}
					switch(GetBaseRace())
					{
					case BARBARIAN:
					case TROLL:
					case OGRE:
						{
							stunTarget = true;
							break;
						}
					default:
						{
							// Image (2014): this will allow non big races when they bash to stun if they have a shield
							if ( IsClient() && skill == BASH )
							{
								ItemInst* inst = CastToClient()->GetInv().GetItem(SLOT_SECONDARY);
								if ( ( inst != NULL && inst->GetItem()->AC > 0 ) || CastToClient()->GetAA(aa2HandBash) > 0 ) // Image: 5/28/2015, two handed bash (aa2HandBash) addition to stun fix for bash
									stunTarget = true;
							}
							break;
						}
					}

				
				if ( stunTarget )
				{
					// these guys can bash and stun
					if ( who->IsClient() )
						who->CastToClient()->Stun(MakeRandomInt(500,1000), true);
					else if ( who->IsNPC() && !who->CastToNPC()->SpecAttacks[UNSTUNABLE] )
					{
						who->CastToNPC()->Stun(MakeRandomInt(500,1000), true);
					}
				}

**Comment by noudess** [comment]
I took a look.  I see code in ours for Bash already and don't know enough to make the changes we need here.  Maybe I'll tackle it if no one that has a clearer understanding already doesn't find the time.
