### ISSUE TITLE
Multi registration

### ISSUE THREAD

**Issue by rabbired** [EQEmu/Server#545]
I have multiple IP addresses, so I put them are used up, the system is proxmox, I establish a server and login server, normal operation and at the same time eqemulator my local login server registration, when I run a second EMU server, registered to the local login server, server list shows two servers, but the landing to go is the second server, the first server do not know where to go, this is why? The login server cannot support multiple local server registration? (I'm sure the IP address of the 2 server has been set up correctly.）
pls help me~
Some people can provide help, thank you very much！

**Comment by Akkadius** [comment]
It's not recommended to run more than one server on the same OS environment. There's no reason to even try to support this as all of the client ports are hardcoded. Spin up another instance or VM. Closing
