### ISSUE TITLE
HP/Mana regen not correctly calculated with RoF2 Client

### ISSUE THREAD

**Issue by thalic** [EQEmu/Server#561]
Using newest server-code and RoF2 Client with 'Character:SoDClientUseSoDHPManaEnd' = 'true', we have the following bug:

Create a new Level 1 Character and start a fight, loose some Mana and/or HP. 
After the fight you see the HP/Mana jumping up and down. 

Example:
Second 1: 40% HP
Second 2: 45% HP
Second 3: 42% HP
Second 4: 50% HP
Second 6: 48% HP

**Comment by thalic** [comment]
Problem also exists on Titanium Client. Tried with HighElf Cleric/Magican and Human Paladin.

**Comment by Akkadius** [comment]
@mackal didn't you do some work with this - had something to do with the hp update packet rate

**Comment by thalic** [comment]
This is now solved!
