### ISSUE TITLE
Mobs agro through walls and up through water

### ISSUE THREAD

**Issue by raidaddicts** [EQEmu/Server#564]
Title says it all, I have the mmf map files, also tried regular map files, latest build and this has been a problem for about 6 months now.  I band aid fixed this on Raid Addicts just by lowering agro radius really low however that sucks.

**Comment by mackal** [comment]
What zones? Details?

**Comment by raidaddicts** [comment]
All zones, everywhere, mobs agro through walls, or up through water even if the underwater flag is set in npc_types.

**Comment by N0ctrnl** [comment]
Sounds like .map file issues to me. Have you tried removing all the mmf files while the zones are down? If those are corrupted, I would expect this to happen. Likewise with a bad .map file.

**Comment by raidaddicts** [comment]
I will try to do that again, but so far I re-downloaded all the maps then converted to  mmf, but I don't think I have ever deleted them then re-downloaded so I'll give that a shot.

**Comment by DanCanDo** [comment]
There's a few people having probs with that wall agro. Only thing I have done, is reduce the agro radius on mobs in dungeons zones (befallen,guk,etc) where it commonly happens. Most of the npc's come with 55
agro radius with default peq download. I had to lower it to 30-35

**Comment by Akkadius** [comment]
This is related to map files not being properly loaded, not a code issue.
