### ISSUE TITLE
eqemu_server.pl, problem with get_mysql_result ? 

### ISSUE THREAD

**Issue by proxeeus** [EQEmu/Server#567]
Hi,
I hope I'm not writing this @ the wrong spot.

This is after a fresh git pull, and a new version of the eqemu_server.pl script.

Basically, world.exe sees that my database is out of date, and tries to update it. The problem I'm facing is, it looks like get_mysql_result (around line 930) has a formatting problem, some parameters are missing an "=" character (password does have it, though), thus leading some mysql commands to never be correctly executed by world.exe

Here's the line I'm talking about (sorry about the formatting...):

`if($OS eq "Windows")
{ 
return `"$path" --host $host --user $user --password="$pass" $db -N -B -e "$run_query"`;
 }
`
I can reproduce the issue by manually entering this kind of "bogus" command on a cmd prompt.

I tried fixing the .pl script but it keeps on redownloading itself.

Here's a picture of the issue:
![image](https://cloud.githubusercontent.com/assets/1784908/19490197/8db22360-956e-11e6-8427-8c23db6481d7.png)

**Comment by Akkadius** [comment]
Should be fixed per https://github.com/EQEmu/Server/commit/16fa32e65bf7dcecc4a90cbc449a9195f4cb8039 go ahead and try again

**Comment by proxeeus** [comment]
There's progress! Now I'm getting another error, but I haven't yet determined if it is on my end or not.

Looks like my mysql credentials aren't resolved for some odd reason...

![image](https://cloud.githubusercontent.com/assets/1784908/19493734/390a5e14-957c-11e6-9509-d30b302b4dd4.png)

**Comment by Akkadius** [comment]
Disable IPv6 on your Windows machine, that should clear up your errors

**Comment by proxeeus** [comment]
Hm. Same thing, I deactivated IPv6 on the machine (via Network adapters & via Registry), same thing. I'll dig deeper tomorrow if I have time!

**Comment by Akkadius** [comment]
It's windows, you have to reboot too

**Comment by proxeeus** [comment]
I did that, of course, multiple times :)

**Comment by Akkadius** [comment]
Then use 127.0.0.1 in your eqemu_config.xml if 'localhost' is still resolving to ::1

**Comment by Akkadius** [comment]
If you're still getting ::1 denial errors, you're still running on IPv6

**Comment by proxeeus** [comment]
Damn, then I must have missed something. I'll investigate further on that front and will let you know. Thank you for your time! :)

**Comment by proxeeus** [comment]
Welp, turns out I didn't put the correct value in the registry (it's 0xFF instead of 0x11), now the address gets properly resolved. Still getting an access denial though O.o

![image](https://cloud.githubusercontent.com/assets/1784908/19495096/3ebfa52a-9582-11e6-82d4-ce3aa5175458.png)

**Comment by Akkadius** [comment]
Ok - so what does your <database> block look like in eqemu_config.xml?

**Comment by proxeeus** [comment]
I think I may have figured it out... my db password was using a lot of special characters (>, ?, * and the like). By creating another user with the same root rights, but a simpler password, world.exe connected flawlessly to MySql!

**Comment by Akkadius** [comment]
That would do it

**Comment by proxeeus** [comment]
Thanks so much for your help! I would never have figured the IPv6 stuff haha :)

**Comment by Akkadius** [comment]
np, glad you got it figured out
