### ISSUE TITLE
Zone Loading - Akkadius

### ISSUE THREAD

**Issue by cream24** [EQEmu/Server#574]
Per PEQ discussion.  Pets dont show up until well after the player is in zone, causing player to begin casting a new pet (via macro).

This also affects player life.  heals start casting on zone (via macro) because the client loads incomplete/not 100% hp

**Comment by joligario** [comment]
Recommend players fix their macros.

**Comment by mackal** [comment]
The pet issue needs to be fixed. They're spawning way too late. It's not even "macro only" speed either. You can zone in and not see a pet in your pet window.

**Comment by Akkadius** [comment]
Should be resolved in: https://github.com/EQEmu/Server/commit/de92c277e0715ecee54bb3c2f04ec9c72684ae41
