### ISSUE TITLE
Akkadius Server Updater - New option for latest daily server build

### ISSUE THREAD

**Issue by cream24** [EQEmu/Server#575]
Please add a new option in the updater to pull the latest daily server build, or on-demand compile, whichever is easier.  This gives us an option for test servers etc: i.e. when new lua exports are added that are required for quests.
Request is for Windows specifically.

**Comment by mackal** [comment]
AppVeyor has a deployment system built into it we might be able to take advantage of.

**Comment by Akkadius** [comment]
Yeah I was going to use the appveyor link for latest. Still keep existing
system in for new installs since it's proven stable builds

**Comment by Akkadius** [comment]
I have this implemented now, latest binaries are grabbed from AppVeyor: http://imgur.com/Cy0XIvH

Commit: https://github.com/EQEmu/Server/commit/b5e324af83e8c4e7a8b17f6412140aafe113619b
