### ISSUE TITLE
Mail to guild does not work

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#577]
Just noticed this.  I am now running RoF2, not sure about other clients.

Attempts to mail to a guild fail for guilds of decent size.   Guilds with only a handful of characters seem to work.  Guilds of 41 and 60 on my server both fail.

The message is : 

Mail delivery failure to <some random part of guild list> (subject Guild).

The subject always seems to be set to Guild in the error message, despite the subject in the message.

If I start a new guild with 3-5 members, it works fine.  Something to do with putting packets together on long messages to client?

**Comment by noudess** [comment]
I tested this a bit.  

41 char guild fails.

Deleted 1st half of a 41 person guild - works.

Deleted 2nd half of same guild (after restoring) - works.

So it has to do with size - not some bad characters in a name or something.  All 41 chars work, just not all at once.

**Comment by noudess** [comment]
Depressing.  This does not fail under Titanium.  Rof2 client bug, or are we packaging up the packets differently and maybe on our side?  I'm not really good enough with the packet layers to help find this.

**Comment by mackal** [comment]
Tried this on RoF2 on PEQ, my guild has 265 player, I got no errors, but I also didn't appear to get a message on other toons :P

**Comment by noudess** [comment]
Fixed by https://github.com/EQEmu/Server/pull/3724.
