### ISSUE TITLE
Bind Sight won't click off.

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#580]
The bind sight buff, when cast on RoF2 (at least) won't click off.

**Comment by Akkadius** [comment]
Is this still an issue

**Comment by noudess** [comment]
Yes.  This actually now doesn't even show as a buff in the buff window.  After you cast bind sight, you're basically outr of control until it drops.

**Comment by noudess** [comment]
Sight Graft does not work at all.

**Comment by fryguy503** [comment]
Is bind sight even useful with the localized packet updates? Mob locations do not update if the bound sight npc is outside of the packet update bubble.

**Comment by joligario** [comment]
https://github.com/EQEmu/Server/pull/1825
