### ISSUE TITLE
Bruax_Grengar.pl error in Scourge Sorcerer Boots description

### ISSUE THREAD

**Issue by Trystanosaurus** [EQEmu/Server#595]
Apologies if this is the wrong place to post this and it should be in the quests/plugins issues instead but there is an error in Bruax_Grengar.pl

Bruax is a necromancer in Qeynos Catacombs who gives out the mold and recipes for creating Scourge Sorceror armour. Note he does give you the correct recipe item, just the wrong description of the materials required.

When you ask him about boots he currently tells you about gloves as the script is currently:
  if ($text=~/boots/i) {
    quest::say("To craft Scourge Sorcerer Gloves you require two [silk thread], klicnik drone bile, two giant field rat whiskers, and a large king snake skin. Once you have the necessary components combine them in your Curing Kit with this Tattered Glove Pattern.");
    quest::summonitem(19561);
  }

From Alakhazam it should be:
  if ($text=~/boots/i) {
    quest::say("To craft Scourge Sorcerer Boots you require two [silk thread], klicnik drone bile, and two large king snake skins. Once you have the necessary components combine them in your Curing Kit with this Tattered Boot Pattern.");
    quest::summonitem(19561);
  }

**Comment by joligario** [comment]
Should be posted on PEQ quests GitHub but I fixed it anyways. Thanks!
