### ISSUE TITLE
Melee Critical Chance rules differ between latest installer and manual binaries

### ISSUE THREAD

**Issue by audiogarden21** [EQEmu/Server#596]
So I ran into a strange issue regarding melee critical chance that I first noticed when I was playing my Warrior that recently hit 12 and noticed that he hadn't crit at all. To further test whether he actually 'could' crit, I pumped up the values of "Combat:ClientBaseCritChance" to 100% (100). That, unfortunately, netted zero results, so I looked at the other rules "Combat:WarBerBaseCritChance", and "Combat:MeleeBaseCritChance" to no avail. I searched around on the forums for some more information and found some good info to help me determine what might have been the cause. My investigation ultimately lead me to the new method used in "attack.ccp" which refers to "Combat:MeleeCritDifficulty". I found it odd that there were no rule_values set for those (also references to throwing and archery), so I added the melee one for testing purposes.

Here's the code snippet that I'm referring to:

`// we have a chance to crit!
	if (innate_crit || crit_chance) {
		int difficulty = 0;
		if (hit.skill == EQEmu::skills::SkillArchery)
			difficulty = RuleI(Combat, ArcheryCritDifficulty);
		else if (hit.skill == EQEmu::skills::SkillThrowing)
			difficulty = RuleI(Combat, ThrowingCritDifficulty);
		else
			difficulty = RuleI(Combat, MeleeCritDifficulty);
		int roll = zone->random.Int(1, difficulty);
`

I also couldn't find any reference to the old rule_values. I remember some time ago when I ran a server that the old values worked just fine. I did however discover that it does, and it doesn't work, currently.

I decided to run further tests so I could determine if there was a database issue or an issue with the binaries. At first I thought it was the database, but then I stumbled onto the real culprit, which has to do with 'certain' binaries.

If you run Akkadius' - awesome I might add, hella fine work - installer, completely fresh with no bots - which download new binaries - then the old rules work just fine. I decided to also try to compile my own binaries - which originally didn't work for some reason as I kept getting errors in VS regardless of what I did, I presume some Windows Updating may have fixed that. I tried compiles both with, and without bots, however neither work with the old rules. They all do just fine with the difficulty rules.

For the record I used the same test database for all four different servers that I ran tests through; my original server that I started with which uses bots, the fresh auto-install with no bot binaries, and two self-compiled binaries with and without bots.

You can replicate this issue yourself simply using Akkadius' installer and connecting to the same database with the two sets of binaries. 

There's another strange issue when loading the bot binaries regardless of install method. Every single time I launch any bot server this update runs:

[World Server] Loading server configuration..
[World Server] CURRENT_VERSION: 1.1.3
[World Server] Added loginserver 127.0.0.1:5998
[World Server] Added loginserver login.eqemulator.net:5998
[World Server] Connecting to MySQL...
[Status] Starting File Log 'logs/world_7672.log'
[World Server] Starting HTTP world service...
[World Server] Checking Database Conversions..
[Update] No script update necessary...
[Info] For EQEmu Server management utilities - run eqemu_server.pl
[Update] Bots Database not up to date with binaries... Automatically updating...

[Update] Issuing database backup first...
[Update] No script update necessary...
[Database] Performing database backup....

Todays Date: 03_27_2017
Operating System is: MSWin32
[db_dumper.pl] Database is peq
[db_dumper.pl] Backup Directory: backups
[db_dumper.pl] Compression SET
[db_dumper.pl] Directory currently exists... Adding files to it...
[db_dumper.pl] Backing up Database peq...
[db_dumper.pl] Command [mysqldump -uroot --host localhost  --max_allowed_packet=
512M --password="eqemu" peq > "backups\peq_03_27_2017.sql"]
[db_dumper.pl] Backup DONE... DB Backup File Size '226816684' (216.31 MiB)
[db_dumper.pl]  ::: You have WinRAR installed as 64 Bit...
[db_dumper.pl] Compressing Database with WinRAR...
[db_dumper.pl] Command ["C:\Program Files\WinRAR\rar" a "backups\peq_03_27_2017.
rar" "backups\peq_03_27_2017.sql" ]

RAR 5.01   Copyright (c) 1993-2013 Alexander Roshal   1 Dec 2013
Trial version             Type RAR -? for help

Evaluation copy. Please register.

Updating archive backups\peq_03_27_2017.rar

Updating  backups\peq_03_27_2017.sql                                  OK
Done
[db_dumper.pl]
Deleting RAW .sql Dump...
[db_dumper.pl] Command [del "backups\peq_03_27_2017.sql" ]
[db_dumper.pl] Final file located: backups\peq_03_27_2017.rar
[Update] Updating bots database...
[Database] Retrieving latest bots database manifest...
[Download] Saved: (db_update/db_update_manifest.txt) from https://raw.githubuser
content.com/EQEmu/Server/master/utils/sql/git/bots/bots_db_update_manifest.txt
[Database] Reading manifest...
[Database] has update: 9017 - '2017_03_26_bots_spells_id_fix_for_saved_shadowkni
ght_bots.sql'
[Database] has update: 9016 - '2017_02_26_bots_spell_casting_chances_update.sql'

[Database] has update: 9015 - '2017_02_26_bots_spell_casting_chances_update.sql'

[Database] missing update: 9014 '2017_02_26_bots_spells_id_update_for_bot_spells
_entries.sql'
[Download] Saved: (db_update/2017_02_26_bots_spells_id_update_for_bot_spells_ent
ries.sql) from https://raw.githubusercontent.com/EQEmu/Server/master/utils/sql/g
it/bots/required/2017_02_26_bots_spells_id_update_for_bot_spells_entries.sql
[Database] has update: 9013 - '2017_02_26_bots_spells_id_update_for_saved_bots.s
ql'
[Database] has update: 9012 - '2017_02_26_bots_npc_spells_update_for_bots.sql'
[Database] has update: 9011 - '2017_02_23_bots_spell_casting_chances.sql'
[Database] has update: 9010 - '2017_02_20_bots_bard_spell_update.sql'
[Database] has update: 9009 - '2017_02_15_bots_bot_spells_entries.sql'
[Database] has update: 9008 - '2016_06_28_bots_inventory_charges_update.sql'
[Database] has update: 9007 - '2016_06_23_bots_camel_case_name_rule.sql'
[Database] has update: 9006 - '2016_04_12_bots_inventory_window.sql'
[Database] has update: 9005 - '2016_04_08_bots_heal_rotations.sql'
[Database] has update: 9004 - '2016_04_07_bots_heal_override_target.sql'
[Database] has update: 9003 - '2016_04_05_bots_pet_spell_id_field.sql'
[Database] has update: 9002 - '2016_03_24_bots_command_rules.sql'
[Database] has update: 9001 - '2016_03_24_bots_command_settings.sql'
[Database] has update: 9000 - '2015_09_30_bots.sql'

[Database] Running Update: 9014 - 2017_02_26_bots_spells_id_update_for_bot_spell
s_entries.sql
[Database] has update: 9017 - '2017_03_26_bots_spells_id_fix_for_saved_shadowkni
ght_bots.sql'
[Database] has update: 9016 - '2017_02_26_bots_spell_casting_chances_update.sql'

[Database] has update: 9015 - '2017_02_26_bots_spell_casting_chances_update.sql'

[Database] has update: 9014 - '2017_02_26_bots_spells_id_update_for_bot_spells_e
ntries.sql'
[Database] has update: 9013 - '2017_02_26_bots_spells_id_update_for_saved_bots.s
ql'
[Database] has update: 9012 - '2017_02_26_bots_npc_spells_update_for_bots.sql'
[Database] has update: 9011 - '2017_02_23_bots_spell_casting_chances.sql'
[Database] missing update: 9010 '2017_02_20_bots_bard_spell_update.sql'
[Download] Saved: (db_update/2017_02_20_bots_bard_spell_update.sql) from https:/
/raw.githubusercontent.com/EQEmu/Server/master/utils/sql/git/bots/required/2017_
02_20_bots_bard_spell_update.sql
[Database] has update: 9009 - '2017_02_15_bots_bot_spells_entries.sql'
[Database] has update: 9008 - '2016_06_28_bots_inventory_charges_update.sql'
[Database] has update: 9007 - '2016_06_23_bots_camel_case_name_rule.sql'
[Database] has update: 9006 - '2016_04_12_bots_inventory_window.sql'
[Database] has update: 9005 - '2016_04_08_bots_heal_rotations.sql'
[Database] has update: 9004 - '2016_04_07_bots_heal_override_target.sql'
[Database] has update: 9003 - '2016_04_05_bots_pet_spell_id_field.sql'
[Database] has update: 9002 - '2016_03_24_bots_command_rules.sql'
[Database] has update: 9001 - '2016_03_24_bots_command_settings.sql'
[Database] has update: 9000 - '2015_09_30_bots.sql'

[Update] Continuing bootup
[World Server] Loading variables..
[World Server] Loading zones..
[World Server] Clearing groups..
[World Server] Clearing raids..
[World Server] Clearing inventory snapshots..
[World Server] Loading items..
[World Server] Loading skill caps..
[World Server] Loading guilds..
[World Server] Loaded default rule set 'default'
[World Server] Loading EQ time of day..
[World Server] Loading launcher list..
[World Server] Reboot zone modes OFF
[World Server] Deleted 0 stale player corpses from database
[World Server] Loading adventures...
[World Server] Purging expired instances
[World Server] Loading char create info...
[World Server] Zone (TCP) listener started.
[World Server] Client (UDP) listener started.
[World Server] New UCS Connection from 127.0.0.1:49977
[World Server] New QS Connection from 127.0.0.1:49978
[World Server] New Launcher from 127.0.0.1:49980
[World Server] New Zone Server from 127.0.0.1:49984
[World Server] New Zone Server from 127.0.0.1:49991
[World Server] New Zone Server from 127.0.0.1:49994
[World Server] New Zone Server from 127.0.0.1:49997
[World Server] New Zone Server from 127.0.0.1:50000

It would be nice to get the bot version up to the same level so we have finer control over crit chances between innate and non-innate classes. You guys have done an awesome job bringing the game up to speed and making it more live like in these past few years. I'm quite impressed, not that that should mean anything to you, but I digress..

I would also like to add that I noticed that my self-compiled bot binaries have 198 total commands whereas the auto-installer only has about a dozen or so.

Thank you for taking the time to read this, and I'll be keeping an eye on this to make sure I can assist with any more details if necessary. Cheers.

**Comment by Akkadius** [comment]
@audiogarden21 the installer regular binaries are a little behind. We have had a major combat revamp to the source since this.

If you run `perl eqemu_server.pl windows_server_latest` it will pull the binaries from the latest source commit.

The installer uses approved stable binaries instead of always pulling the latest and potentially unstable binaries.

**Comment by audiogarden21** [comment]
So does that mean that the old rules are being phased out and what I'm experiencing is the path that is to be taken, in that the new rules (difficulty) will be the norm?

**Comment by Akkadius** [comment]
Everything now is meant to be live like, the new changes were actually compensated in the PEQ database and also via https://github.com/EQEmu/Server/blob/master/utils/sql/git/optional/2017_01_16_NPCCombatRebalance.sql

Or you can pull the latest PEQ database with the eqemu_server.pl utility script - but this will overwrite characters.

There is no clear documentation on the combat changes as of yet, @mackal did the work on it

**Comment by Uleat** [comment]
Thank you for posting your update log too.

I know about that particular issue..but, have had a hard time figuring out how to properly trigger that.

That definitely helped to clarify the issue!

**Comment by audiogarden21** [comment]
@Akkadius Ahhhh, I see what's going on. That explains the discrepancy between the - what I now know as "stable" and "unstable" - binaries. I just ran a test going off what you posted and the unstable binaries use the new rules while the stable one uses the old rules - I didn't touch the database so I could rule out the binaries. 

So I was correct in that the old rules are being phased out. Well that's good to know, even if I would have preferred the old way, but of course that's all part of the transition. I'm sure it won't remain that way forever, as in we'll have more options down the line, similar to what we have no, perhaps.

And here I was thinking that the bot binaries were lagging behind. It seems it was quite the opposite.

@Uleat You're welcome. By the way if you need any testing of sorts, I'm here to help. I know my way around Papyrus Scripting Language so I can read C++ (also learned some basic some years ago, wrote a damage/delay calculator for EQ ;), I'm just not fluent in writing it. 

That said, I'm pretty good at hunting down bugs so feel free to hit me up. I already put in a good amount of work - with what I could do at my current skill level - to help the community by creating the Spellcrafter's Handbook a few years back. Nobody uses it anymore after the wiki went up that deprecates it, but I was happy to do it. I've been away from Emu for quite a while now but I'm back and ready to help! I think my experience modding Fallout 4 - and teaching myself scripting - has greatly aided my ability to understand what I'm looking at when perusing the code.

**Comment by mackal** [comment]
Just tested on PEQ. Had to get some dex buffs to make it more common.
