### ISSUE TITLE
spell awareness not working in certain cases

### ISSUE THREAD

**Issue by cream24** [EQEmu/Server#599]
this is recent, within a few days.  this may be a difference in ae vs single target spells or something like that, raid leader/group leaders all had spell awareness leader aa (green/active) but in some cases it would not work:

[Sun Apr 09 16:01:43 2017] a discordling enchainer begins to cast a spell. <Discordling Ruin>
[Sun Apr 09 16:01:46 2017] a discordling taskfiend begins to cast a spell. <Discordling Ruin>
[Sun Apr 09 16:01:46 2017] a discordling taskfiend begins to cast a spell. <Discordling Ruin>
[Sun Apr 09 16:29:06 2017] Zellucheraz the Ancient begins to cast a spell.
[Sun Apr 09 16:29:46 2017] Zellucheraz the Ancient begins to cast a spell.
[Sun Apr 09 16:31:20 2017] Zellucheraz the Ancient begins to cast a spell.

**Comment by mackal** [comment]
Spell Awareness is level capped.
