### ISSUE TITLE
SHD Harm Touch, Improved Harm Touch, and Leech Touch

### ISSUE THREAD

**Issue by mackal** [EQEmu/Server#6]
Details: http://www.peqtgc.com/phpBB3/viewtopic.php?f=17&t=13837

It seems there are some errors with their timers and maybe spell? HT will say 35 mins or w/e reuse but once you zone it goes back to what it would of been w/o the redux AA

EDIT: Underfoot at least.

**Comment by Akkadius** [comment]
Were these fixed with the new AA rework? @KimLS @mackal  ?
