### ISSUE TITLE
swarm pet enrage/flurry are counting as NPC for chat filter, rather than pet

### ISSUE THREAD

**Issue by cream24** [EQEmu/Server#600]
swarm pet enrage/flurry are counting as NPC for chat filter, rather than pet.  this makes it impossible to isolate them from actual npc rampage/flurry messages.

[Sun Apr 09 15:14:56 2017] Lube`spet executes a FLURRY of attacks on a discordling taskfiend!

**Comment by Aeadoin** [comment]
Should be fixed by #2444

**Comment by Aeadoin** [comment]
This should be marked resolved. fixed under #2444
