### ISSUE TITLE
emote/pet message text lacks space between name and the next word: name'spet,

### ISSUE THREAD

**Issue by cream24** [EQEmu/Server#601]
e.x
[Sun Apr 09 15:14:56 2017] Lube`spet executes a FLURRY of attacks on a discordling taskfiend!

**Comment by mackal** [comment]
This is all on the client, it doesn't seem to like that ... I'll have to capture some packets on live I guess :(

**Comment by Kinglykrab** [comment]
Client-side issue, cannot be fixed server-side.
