### ISSUE TITLE
Group Bugs

### ISSUE THREAD

**Issue by spdkils** [EQEmu/Server#607]
If the leader is out of zone (nullptr) and anyone else in group clicks disband, it bugs the group, and knocks it apart. Leaving the poor soul who clicked Disband with a broken group.

This is because DelMember calls DisbandGroup() if the leader is EVER a null pointer when it's called. With a return true; :-/

So, there are a LOT of situations to cause that to happen.

Leader leaves zone, you click disband. (You killed group)
Leader dies (he is null pointer before ~Bot is called, so you Killed the group)
You camp a bot while leader is out of zone (You killed the group)
etc etc

**Comment by Akkadius** [comment]
Groups and raids have been needing to be redone for quite a while

**Comment by spdkils** [comment]
Hrm, maybe I'll take a stab @ it... May take me a few weeks... is anyone else working it? I can spend some time...

**Comment by mackal** [comment]
We had code that failed to work in the case where leader left, I changed this so it disbanded the group since it was leaving clients in states that could crash the client. It just wasn't working right. Groups are rather complex and really need to be rewritten. It's not that simple of a task sadly.

**Comment by spdkils** [comment]
I spent 3 hours looking @ it last night... I realized very quickly, it is not as simple, as I thought groups would be. After breaking groups 6 different ways, and multiple crashes, I realized I would have to learn a lot more about how this is put together before being able to do anything effective. :)
