### ISSUE TITLE
2 slot sewing kit can make 4 item combine (generic issue also true)

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#610]
Looks  like the code does not enforce container size when all the components do not fit.

**Comment by noudess** [comment]
To give better detail.  This happens when you click a recipe and the GUI loads the items in.  It loads more items into the container (virtually I guess) than it can hold.

**Comment by noudess** [comment]
Take a small sewing kit and making a gnoll fur patch.

**Comment by daerath** [comment]
HandleAutoCombine does not perform any checks against container size or # of components required in the recipe.  However, I don't know if that matters on live so I'm going to check that.

**Comment by mackal** [comment]
I'm pretty sure live doesn't define recipes to use generic typed containers either. It's just an item ID of a container (I do think they do a size check anyways)

**Comment by noudess** [comment]
Second check unneeded as they can't put the items in without the recipe since they won't fit?

**Comment by daerath** [comment]
The second check is more to catch people packet hacking

**Comment by noudess** [comment]
ah thx
