### ISSUE TITLE
Group loot is checked before raid loot.

### ISSUE THREAD

**Issue by spdkils** [EQEmu/Server#611]
When you invite Group leads to raid, when a mob dies, it checks group loot before raid loot, with an IF/Else If. So raid loot settings do not work.

I 'think' it should always check raid loot 1st, and IF you're not in a raid, then check group.

I'm pretty sure, group loot shouldn't override raid loot, or else people could KS raid targets, and loot.

If this is true, I have a fix already, I can just do a pull request...

**Comment by mackal** [comment]
Line of code?

**Comment by spdkils** [comment]
2365 in attack.cpp checks group, then else if checks raid.

Pretty sure that should be reversed.

**Comment by mackal** [comment]
Well, you can't be grouped and raided, so it doesn't matter.

**Comment by spdkils** [comment]
hrm, but I can invite 5 people to group, then invite them to raid, then they are in a group in the raid. and you can still see group members. When I raid invite it kicks ME from group, but not the people I invited, then I can invite people again.

**Comment by spdkils** [comment]
Oh, also if you're in a group with bots, and create a raid, you're still in group, and you can then re invite your bots. But that must be a glitch.

However, if I invite someone who is in a group, they come in as a group. So more grouping behavior I guess.

So everyone who has been doing raid loot, must be just inviting individuals, and not inviting group leads i suppose.

**Comment by mackal** [comment]
IsGrouped will return false though.

**Comment by spdkils** [comment]
I'll double check, I reversed the loot order and it worked as I thought, but maybe it didn't need reversed. I'll debug it, I could be wrong. I have never gotten raid loot to work, but I've always shown up as if I'm in a group in the raid window. I assumed it would show me as grouped, since I still have group members, and group buffs still work.

**Comment by spdkils** [comment]
NPC::Death(Mob *, int, unsigned short, EQEmu::skills::SkillType) true <--- Returned true IsGrouped with debug....

It's a bot problem again, causing this.

**Comment by spdkils** [comment]
The group without bots, you are correct returned false, the group that started the raid, that had a bot member upon raid creation is returning true.

**Comment by mackal** [comment]
Bots aren't allowed in raids and yeah, probably bots causing issues.

**Comment by spdkils** [comment]
Okay, I spent the last 30 minutes documenting the behavior, and the results.
IsGrouped() is returning True if you group with a bot before, or after raid creation.
So while the bots are never in raid, it does cause the looter lookup to get tripped up.

Did a bunch of tests, with a debug action of just reporting killer->IsGrouped()

All players, no problem. Mix of players and bots roaming around, it gets tripped up.

I did reverse the grant looter code, and it deals with the symptom, but doesn't actually function how players are supposed to function.

In the group/raid revamp, I guess bots will need to revamped in the groups/raid code.

Don't think it should cause other problems, reversing the if else/if. I know it's not the right fix, but it still masks the problem some....

**Comment by spdkils** [comment]
I feel like I'm being a pest, so I apologize for that.
However when working with bots, being able to raid together 4 or 5 players, then have them summon bots to fill out their groups, or fill slots in their groups is nice for non-single player hybrid raids.

Reversal of this code doesn't fix the 'problem' of players returning grouped, but it does fix what doesn't function on the raid... Being able to assign raid looters, and have it function.
