### ISSUE TITLE
Messages not showing in telnet console

### ISSUE THREAD

**Issue by N0ctrnl** [EQEmu/Server#618]
After issuing the 'echo off' and 'acceptmessages on' commands via telnet, messages are still not shown.

Xackery has more thoughts, but pointed to maybe acceptmessages not being completely finished(?)

**Comment by Akkadius** [comment]
Resolved in https://github.com/EQEmu/Server/commit/31d8336b4b21baa7af95c6f7d060a24ef62703a6
