### ISSUE TITLE
xtarget npc entries when no interaction has been made

### ISSUE THREAD

**Issue by Akkadius** [EQEmu/Server#627]
http://i.imgur.com/g7kp40C.jpg

Client leaves zone - empty xtarget list

Client comes back - same entries persist - same result after camp

Non-combat NPC's with no hatelist entries

**Comment by mackal** [comment]
Fun fact! Groups (and raids) don't get cleaned up when everyone leaves ...

**Comment by Akkadius** [comment]
Where is the janitor?!

**Comment by joligario** [comment]
Custodian!!

**Comment by AthrogatePEQ** [comment]
Mackal!
