### ISSUE TITLE
JSON eqemu_config conversion

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#630]
* Add support for eqemu_config using common/json_config code
* Find/Make a binary that converts eqemu_config to json

**Comment by xackery** [comment]
* Locked element will be parsed and convert to Locked = "", which isn't the ideal solution. Needs more logic to convert cleaner.

**Comment by xackery** [comment]
The perl script should do the following:
* [ ] Verify eqemu_config.json does not exist.
* [ ] Download and execute the xmltojson binary to convert eqemu_config.xml to eqemu_config.json.
* [ ] Capture any signals (1) from the executed xmltojson binary, and assume if non-zero, failure (error is outputted to stdout).
* [ ] Optionally delete eqemu_config.xml
* [ ] Parse eqemu_config.json once it exists, and use it for future configuration runs.

**Comment by Akkadius** [comment]
Will be bringing this over into master in the near future
