### ISSUE TITLE
Expeditions (Dz OPCode)

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#634]
* [ ] Check compatibility with Titanium, UF, and SoF to see if /dz prefixed commands are supported

Typing /dz in game shows a help menu.
alt+z for expeditions window.

* [ ] DzAddPlayer - Used in ExpeditionAddPlayer(). /dzAddPlayer <playername> - This command can only be used by expedition leaders to add a player to their expedition instance. The player to be added has to approve or this command fails.
* [ ] DzChooseZone - 
* [ ] DzCompass - Used in MarkSingleCompassLoc
* [ ] DzExpeditionEndsWarning - Used in ExpeditionWarning
* [ ] DzExpeditionInfo - Used in ExpeditionInfoUpdate and ExpeditionQuit
* [ ] DzExpeditionList - 
* [ ] DzMemberList - 
* [ ] DzInviteRaid -
* [ ] DzInviteTask -
* [ ] DzJoinExpeditionConfirm - Used in ExpeditionAddPlayer()
* [ ] DzJoinExpeditionReply - 
* [ ] DzLeaderStatus - 
* [ ] DzListTimers - /dzListTimers - This command will list any outstanding replay timers you have for all expeditions. This is the amount of time you must wait before being allowed to enter another instance of that zone.
* [ ] DzMakeLeader - /dzMakeLeader <playername> - This command can only be used by expedition leaders to transfer leadership to a new player.
* [ ] DzMemberStatus - 
* [ ] DzPlayerList -  /dzPlayerList - This command can be used by any player currently assigned to an expedition to list all members of the expedition.
* [ ] DzRemovePlayer - /dzRemovePlayer <playername> - This command can only be used by expedition leaders to remove a player from their expedition instance.
* [ ] DzSwapPlayer - /dzSwapPlayer <playername to remove> <playername to add> - This command can only be used by expedition leaders to remove a player from their expedition instance.
* [ ] DzQuit - Used in ExpeditionQuit(). /dzQuit - This command removes you from your current assigned Expedition.

Task Commands:
* [ ] TaskAdd - /taskadd <name>
* [ ] TaskRemove - /taskremove <name>
* [ ] CompareTask - /comparetask
* [ ] MakeTaskLeader - /maketaskleader <name>
* [ ] TaskQuit - /taskquit

unknown raid status
/setloottype # - (4 is the number for open loot to the entire raid)
/makeraidleader <player_name>

out of era:
/compareexpedition <-- not implemented in ROF2

* [ ] eq->player_name declared while encoding DZJoinExpeditionConfirm, but does not exist? Commented out for now.

Someone describing feature:
* Raid and Dynamic zone invites are completely different entities.  Any late comers that join us require both a raid and instance invite. 
* If you are in the raid, but havn't been invited to the instance, DO NOT click or attempt to zone in.  I say this because, each time you do, the raidleader (me) gets spammed with 1 line of red text for each person in the raid.
* Never click or request an instance while in the raid.  We get the instance when we have the required numbers, or close to it.  This is important, because it cuts down on having to constantly add people to the instance as they arrive.
* Yeah, different mobs give different expeditions. Until you've beaten smith/all sewers you request a sewers expedition from the high priest in barindu. After, you request from the other guy near qinimi entrance (coming from qinimi he's to your right by the corner of the pyramid), forget his name. Then vxed/tipt use the apprentice in the pond towards the east. Yeah, alt-z works, also there's a number of /dz commands (dynamic zone) you can use, like /dzaddplayer <name> and /dzremoveplayer <name> that go cross zones. Very handy.
* t is instanced like many of the later raids, you form a raid up, someone requests the instance (or DZ) and then you zone into your very own copy of the raidbosses lair, generally a complete copy of the zone they reside in, complete with minor named and possible rare spawns/loot.
This is accomplished through NPCs (in classic kunark and velious so far) called "Agent of Change" (Its a big red Kedge) that are located somewhere near the zone which the boss resides in.
I don't think they have any post anywhere about it.
A bit more info on the AoC. You must be in a raid of at least 6 people (on or offline, level doesn't matter) say "Danger" to trigger the DZ, and then "ready" to enter the zone. You must be in the main pick of a zone to trigger/zone into a DZ.
Classic
Hate - Resides in South Ro, near the Specter Tower.
Fear - Directly outside the Portal to PoF proper.
Naggy - Outside the tunnel to SolB.
Vox - To the south of Permafrost main entrance, outside the icegiant walls.
Phinny - on the island in the center of Dagnor's Cauldron.
Sky - in East Freeport, up a hill on the south end of docks (near where you'd zone out of Sky)
Kunark
Gore - In FV just before you enter Dreadlands.
Talendor - In OT at the zone to Skyfire
Sev - in FoB just outside the EJ zoneline.
Venril Sathir - To the right as your entering KC in DL.
Trak - Just outside Sebilis Orb.
VP - Havn't bothered looking yet!
* Picks are based on the zone population. If there are too many players in a zone, a new pick will spawn. They are called picks because you use the command /pick. Anyone can enter any pick, as long as the one you are going to isn't too crowded. When you 'pick over' you will be at the same exact location, just in a new copy of the zone. There are no lockouts on picks. If there are zero players inside, they stay open for 45 minutes or so. Named mobs will spawn in picks, but not raid targets, those are only in the base pick. These raid targets are considered 'open world'. The number of players needed to spawn new picks varies from zone to zone. There have been 13+ picks of sebilis on busy nights.
* DZs are based on the dynamic zone technology. There will be a mob called Agent of Change that you interact with to start an instance. Starting an instance requires at least 6 people. Members of the group/raid will be asked if they want to join th expedition. Lockout timers are shown in the expedition window. As soon as you join, you get a 2.5 day lockout. When you kill anything inside, it gets upgraded to a week timeout. The AoC to create the instance is always outside the zone where you are going to do the raid. Saying 'ready' to the AoC once the DZ has been created will bring you to the matching AoC inside the zone. Sometimes this is near the zone in (seb, KC) other times it is deeper in the dungeon (kedge, Solb). Saying 'leave' to the second AoC will bring you outside. A DZ will have all mobs spawned in the zone, including some named, but they will not repop like a normal zone.

Baseline: I took sorvani's work from the ImplmentExpeditions branch (Back in 2014?) and started incorporating them into latest eqemu (which had some lua calls to Dz*, and other lingering Dz-related OP calls)

**Comment by xackery** [comment]
This task may be too big for me at this time, I'm pretty busy and also not knowledgeable with a lot of the needed requirements, so if anyone else wants to pick this up just let me know!

**Comment by joligario** [comment]
I think this is complete now? cc: @hgtw

**Comment by hgtw** [comment]
Yea this can be resolved, all the expedition specific stuff is implemented
