### ISSUE TITLE
Build error "Unknown number type, check LUA_NUMBER_* in luaconf.h"

### ISSUE THREAD

**Issue by zmertens** [EQEmu/Server#642]
The error message is thrown on `line 74` in `zone/lua_bit.cpp`; looking through the repository there does not appear to be any file named `luaconf.h`.

Update: Just realized that `luaconf.h` is part of the Lua source code, I have it in my `/usr/include/luaconf.h`, so I'm not sure why it's not getting picked up by the build system.

**Comment by Akkadius** [comment]
Closing this unless this is an actual issue still
