### ISSUE TITLE
ROF2 Objects Z Offset

### ISSUE THREAD

**Issue by Akkadius** [EQEmu/Server#645]
Objects/ground spawns/tradeskills are higher off the ground in this client - need to offset Z in spawn packets

**Comment by mackal** [comment]
I've looked at the packets on live and I'm pretty sure objects are still floating. I know secrets said we might be using the wrong OP code, but I'm 99% sure we aren't. Gotta be something else we are missing.

**Comment by Kinglykrab** [comment]
This has been resolved.
