### ISSUE TITLE
Installer failure, debian.

### ISSUE THREAD

**Issue by Synesso** [EQEmu/Server#654]
I created the following Dockerfile

```
FROM debian:7
RUN apt-get update
RUN apt-get install -y wget
RUN wget --no-check-certificate https://raw.githubusercontent.com/EQEmu/Server/master/utils/scripts/linux_installer/install.sh -O install.sh
RUN bash install.sh
```

It fails after about 10 minutes with 

```
E: Unable to locate package mariadb-server
install.sh: line 144: mysql: command not found
install.sh: line 208: mysql: command not found
install.sh: line 209: mysql: command not found
install.sh: line 210: mysql: command not found
--2017-08-16 11:52:29--  https://raw.githubusercontent.com/EQEmu/Server/master/utils/scripts/eqemu_server.pl
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.28.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.28.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 79062 (77K) [text/plain]
Saving to: `eqemu_server.pl'

     0K .......... .......... .......... .......... .......... 64%  809K 0s
    50K .......... .......... .......                         100%  553K=0.1s

2017-08-16 11:52:30 (695 KB/s) - `eqemu_server.pl' saved [79062/79062]

[Copy] folder doesn't exist, creating 'updates_staged/'
[Update] No script update necessary...
[Error:eqemu_server.pl] MySQL path not found, please add the path for automatic database upgrading to continue...

chmod: cannot access `/home/eqemu/server/*.sh': No such file or directory
The command '/bin/sh -c bash install.sh' returned a non-zero code: 1
```

When I ran it HEAD was bb8c6da0b446f09a97e55a2377d4d5894ec49366

Are there any pre-reqs that I needed to do?

**Comment by N0ctrnl** [comment]
Uhh, install mysql? Also, Docker is not a supported configuration for the installer. You're going to have to do WAY more to get that working.

**Comment by Synesso** [comment]
So the install script has pre-reqs. Would be good to get them in the README. 
IRT Docker, it was just a mechanism for getting a fresh Debian install & otherwise not relevant. You can read this issue as "install.sh fails on clean Debian LTS".

**Comment by Akkadius** [comment]
As @N0ctrnl mentioned - we don't support Docker in any way shape or form for the installer.

We keep the installer updated with the various OS's mentioned in the Readme and will do verifications every once in a while when a new OS release is prominently stable.

I did latest Debian 9 for you just now and everything went smooth: http://i.imgur.com/janLQtY.png

**Comment by mackal** [comment]
Debian 7 does not have mariadb apparently. I'm not sure wheezy contains a new enough GCC either.

**Comment by Synesso** [comment]
Thanks @mackal - that makes sense.
