### ISSUE TITLE
Bot Bug After Zoning

### ISSUE THREAD

**Issue by TribalBeast** [EQEmu/Server#657]
In current source with fresh database, bots become untargetable after zoning with them.
Camping and respawning does the trick, but only until you zone again.
I've tested this out in several ways, including downloading precompiled binaries from the
eqemu_server.pl script. I reverted back to older code and it's not an issue.
The fresh source I compiled and database was untouched, unedited, (except for enabling bots).

**Comment by Akkadius** [comment]
Not sure there is anyone source capable who is working on bots at this time. Since they are not officially supported I'm not sure when this will be looked at

**Comment by Uleat** [comment]
Closing as issue has been addressed.
