### ISSUE TITLE
Server Rule: Loot Count Modifier

### ISSUE THREAD

**Issue by TurmoilToad** [EQEmu/Server#670]
https://github.com/EQEmu/Server/blob/bc348dadada3f01261537a2c4fbd1ebec24ca1c6/zone/zone.cpp#L2216

Would it be possible to implement a server rule for Loot Count Modifier so that we can tweak the number of drops added to the loot tables in the zone?  IE Adventure::LDONLootCountModifier 10 Comment: reduce this number to increase the amount of drops.

**Comment by Akkadius** [comment]
Are you talking specifically loot in general - or just for LDONs?

**Comment by TurmoilToad** [comment]
Just for the LDON Collection Adventures

**Comment by Kinglykrab** [comment]
Resolved here: https://github.com/EQEmu/Server/pull/2694
