### ISSUE TITLE
Monk Intimidate tosses invalid message at death of mob

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#675]
My level 30 monk ujses intimidate several times during a battle.  When the mob dies, I nearly always get a "You can't intimidate yourself' message, even if I haven't pressed intimidate for sometime.

I'll try and look at the code soon.

**Comment by mackal** [comment]
Intimidate fires off on a timer after the skill is used.

**Comment by noudess** [comment]
Ah let me test and make sure that  it is much later.  I'll do some battles where I don't intimidate past maybe mid way.

**Comment by mackal** [comment]
Pretty sure this is a client generated message too.

**Comment by noudess** [comment]
It is what you said.  Closing this out.
