### ISSUE TITLE
NATS feedback

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#708]
* [x] AM] mackal: @Shin Noir also, remove EntityList::ListNPCs(), it's not needed, [10:20 AM] mackal: you can get a const references to the underlying unordered_map instead of making a new map
* [x] [9:51 AM] mackal: @Shin Noir don't commit the protobuf generated files - [9:54 AM] mackal: https://cmake.org/cmake/help/v3.9/module/FindProtobuf.html
* [ ] !movecharacter <name> <zone>. If offline, update db. If online, teleport them to safe spot of provided zone

**Comment by xackery** [comment]
* [ ] After my recent merge, unknown0344 was changed/removed? 
* [ ] meleepush_xy was renamed heading
* [ ] meleepush_z was changed to pitch

I did not update the proto files to reflect this yet

**Comment by xackery** [comment]
* [ ] Add protoc.exe to dependencies for autogenerating

**Comment by xackery** [comment]
Tells system - It looks like to support tells, the chain of events is like.. client -> zone -> (ServerOP_ChannelMessage) -> world -> (ServerOP_ChannelMessage) -> zone -> client. The problem with relaying tells to other sources is that the whole tell system is designed to be instantaneous. Requests would need time to discover if it succeeds or not. I can't do a timeout too elegantly since it will lock the thread the tell was sent through (likely main thread).. I could toss the request into it's own thread, and you won't get a response to your tell reply until a timeout or a response happens.. this is something i'll consider adding later. It would be really powerful to extend this sort of functionality for quests, too.

**Comment by Kinglykrab** [comment]
Any chance any of this will be used @xackery?

**Comment by xackery** [comment]
Nah, it's safe to close this. I don't think with the current design it makes sense. Maybe temp0's new implementation will mirror some features this offers.

We probably should keep the branch (xackery/nats) but can close this issue for time being.
