### ISSUE TITLE
Pets ignore weapon proc level on offhand

### ISSUE THREAD

**Issue by Didymuser** [EQEmu/Server#710]
Testing this a bit and found that the pets dont check for item proc level wen its on the offhand swing.
That's what it looks like at least.

**Comment by xackery** [comment]
If you can @Didymuser try running `#logs set gmsay 6 3` with the situation above.
https://github.com/EQEmu/Server/blob/7857bc45fbd3ff4702b575b737550a83bac0b656/zone/attack.cpp#L3989

primary and offhand code both seem to run TryWeaponProc for both NPC and players, in fact this is the only logic anywhere and I don't see any things that would cause offhand not to honor level rules. It needs to be the level2 field in items, though

**Comment by Kinglykrab** [comment]
Not seeing this issue with testing.
