### ISSUE TITLE
Bot spawn, illegal mix of collations

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#724]
Illegal mix of collations
![image](https://user-images.githubusercontent.com/845670/36942596-23cb47ae-1f2b-11e8-94cc-55a5c17872bf.png)

My PEQ copy may be a bit off, but should be repeatable

**Comment by xackery** [comment]
looks like my guild_members, guilds is latin1_swedish_ci.. vw_guild_members hmm it's a view, so.. my database defaults to utf8_general_ci.

This may just be an edge case for me.. feel free to verify. it's easy to replicate.

**Comment by Uleat** [comment]
We'll have to keep an eye on this...

My view is swedish as well as the 2 tables.

**Comment by Uleat** [comment]
Is this still an issue?

**Comment by Akkadius** [comment]
Not sure this is still a thing cc @Kinglykrab @Aeadoin
