### ISSUE TITLE
#scribespells isn't aware of ranked spells

### ISSUE THREAD

**Issue by mackal** [EQEmu/Server#727]
This command doesn't handle this correctly.

**Comment by Kinglykrab** [comment]
Could we fix this by adding a `spell_rank_groups` table and at least putting the default ranked spells groups in there so we can have a way to separate the ranks? Or is there something in the spell itself that links it to the next/previous spell? I know there’s a rank column, but doesn’t seem to be anything other than an indicator.

**Comment by mackal** [comment]
I think this could be fixed by not adding a new table. Just need to check if the spell has a rank and find the previous already mem'd rank and overwrite it.

**Comment by Kinglykrab** [comment]
> I think this could be fixed by not adding a new table. Just need to check if the spell has a rank and find the previous already mem'd rank and overwrite it.

How do you know the previous memorized rank’s spell ID?

**Comment by mackal** [comment]
`SPDat_Spell_Struct::spell_group`

**Comment by Kinglykrab** [comment]
Ah gotcha, wasn’t aware that column was used for that. Sounds like something easy to fix though.

**Comment by mackal** [comment]
> Ah gotcha, wasn’t aware that column was used for that. Sounds like something easy to fix though.

I would double check with actual data, but they do match for each spell in the series, didn't check much further than that ... But I don't think they use anything else to decide ...
