### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Showerrodney** [EQEmu/Server#728]
Windows 7 - x64, clean install.

`Can't locate JSON.pm in @INC (@INC contains: /usr/lib/perl5/5.8/msys /usr/lib/pe
rl5/5.8 /usr/lib/perl5/site_perl/5.8/msys /usr/lib/perl5/site_perl/5.8 /usr/lib/
perl5/site_perl/5.8 /usr/lib/perl5/vendor_perl/5.8/msys /usr/lib/perl5/vendor_pe
rl/5.8 /usr/lib/perl5/vendor_perl/5.8 .) at eqemu_server.pl line 322.
BEGIN failed--compilation aborted at eqemu_server.pl line 322.`

Any help appreciated.

**Comment by Akkadius** [comment]
Did you use the installer for this?

Make sure to do a `sudo cpan install JSON` - we will have to make appropriate adjustments in the installer

**Comment by Showerrodney** [comment]
Sorry for not being clear first time - I used the installer downloaded from https://github.com/EQEmu/Server/wiki/Windows-Server.

Thanks for the fast reply.

**Comment by Akkadius** [comment]
The message you pasted is from a Linux machine

**Comment by Showerrodney** [comment]
Message is pasted directly from the windows console (on Windows 7 64bit) that appears when I run eqemu_install.bat (as admin per instructions).

**Comment by Akkadius** [comment]
Hmmm - I'm not sure how it could - we don't use Perl 5.8 in the installer as it is Perl 5.12 - /usr/lib/perl5 is a Unix path - not a windows

**Comment by Showerrodney** [comment]
Realised my clean install of Win7 wasn't as clean as I'd assumed: found a copy of MinGW lurking, complete with its install of Perl 5.8. 

Issue solved, sorry for the waste of time!

**Comment by Akkadius** [comment]
Sounds good!
