### ISSUE TITLE
[Installer] Perl version mismatch

### ISSUE THREAD

**Issue by Trystanosaurus** [EQEmu/Server#742]
Using the server installer zone.exe fails to load, it says it can't find perl526.dll. The installer however only installs version 5.12.

**Comment by Akkadius** [comment]
This is from AppVeyor autobuilds that have changed recently, the installer shouldn't be using AppVeyor by default. I will have to adjust this, in the meantime use 

```perl eqemu_server.pl windows_server_download``` and not

```perl eqemu_server.pl windows_server_latest```

**Comment by Trystanosaurus** [comment]
Ah, I had grabbed the latest appveyor autobuild, so that's what it was. This issue can probably be closed since you seem to have it all in hand anyway. Thanks for the confirmation.
