### ISSUE TITLE
[Titanium] unable to find starting zone

### ISSUE THREAD

**Issue by Trystanosaurus** [EQEmu/Server#743]
When making new characters in titanium the emulator isn't finding their start zones properly.

I'm not sure if I've got anything set up incorrectly but I am now using a clean install from the installer.

The problem seems to be in /world/worlddb.cpp from aroun line 355
```
> 	// see if we have an entry for start_zone. We can support both titanium & SOF+ by having two entries per class/race/deity combo with different zone_ids
> 	std::string query = StringFormat("SELECT x, y, z, heading, start_zone, bind_id, bind_x, bind_y, bind_z FROM start_zones WHERE zone_id = %i "
> 		"AND player_class = %i AND player_deity = %i AND player_race = %i",
> 		in_cc->start_zone, in_cc->class_, in_cc->deity, in_cc->race);
```

As far as I can see Titanium sends a player choice, and SoF+ sends a zone id. The database is set up for both but as far as I can see it's only doing a database query for the SoF situation.

Starting a Iksar (race 128) Monk (class 7) in titanium (player_choice 12) I get the following in my log..
```
[World Server] Found 'TitaniumStartZoneID' rule setting: -1
[Status] SoF Start zone query: SELECT x, y, z, heading, start_zone, bind_id, bind_x, bind_y, bind_z FROM start_zones WHERE zone_id = 12 AND player_class = 7 AND player_deity = 203 AND player_race = 128

No start_zones entry in database, using defaults
[World Server] Attempting autobootup of cabwest (82:0)
```

So it's thinking player choice (12) is a zone_id, it of course can't find anything and spawns me in the default location. For this combination it's a particular problem because the default location for Iksar is cabwest but they should spawn in cabeast, meaning the character doesn't get it's starting items correctly.

This could I think be fixed by simply having an isTitanium check before the database is checked and if it is Titanium do..
```
std::string query = StringFormat("SELECT x, y, z, heading, start_zone, bind_id, bind_x, bind_y, bind_z FROM start_zones WHERE **player_choice**= %i "
		"AND player_class = %i AND player_deity = %i AND player_race = %i",
		in_cc->start_zone, in_cc->class_, in_cc->deity, in_cc->race);
```

I've temporarily fixed it on my core by duplicating all rows of the start_zones databes (like the comment suggests). Swapping the content of zone_id in the database with player_choice, which seems to work from the small amount of testing I've done. 

It feels like it'd be better solved in the core though since the database already has separate fields that can be used for Titanium and SoF, it just needs to check which client we're using and do a different query for each then there's no need for duplicates in the database.

**Comment by ECXevian** [comment]
I have a fix for this in code with no db changes. We're using Titanium on our server exclusively and this has been an issue.

The query just needs to look at `player_choice` instead of `zone_id` for Titanium.

``` 
       std::string query;

        if (isTitanium) {
                query = StringFormat("SELECT x, y, z, heading, start_zone, bind_id, bind_x, bind_y, bind_z FROM start_zones WHERE player_choice = %i "
                        "AND player_class = %i AND player_deity = %i AND player_race = %i",
                        in_cc->start_zone, in_cc->class_, in_cc->deity, in_cc->race);
                LogInfo("Titanium Start zone query: [{}]\n", query.c_str());
        }
        else {
                query = StringFormat("SELECT x, y, z, heading, start_zone, bind_id, bind_x, bind_y, bind_z FROM start_zones WHERE zone_id = %i "
                        "AND player_class = %i AND player_deity = %i AND player_race = %i",
                        in_cc->start_zone, in_cc->class_, in_cc->deity, in_cc->race);
                LogInfo("SoF Start zone query: [{}]\n", query.c_str());
        }

**Comment by joligario** [comment]
#1090
