### ISSUE TITLE
Cannot memorize spells in spellbook from pages 61 and up

### ISSUE THREAD

**Issue by TheMaskedShadow** [EQEmu/Server#763]
Memorizing spells from pages 1 to 60 works fine.

The client becomes partially unresponsive when trying to memorize spells on pages 61 and up and the spell disappears.

Uleat pointed that issue might be caused by line 852 (and potentially 854) from this file https://github.com/EQEmu/Server/blob/master/common/eq_packet_structs.h#L852

**Comment by Uleat** [comment]
Pretty sure this was addressed..please re-open if not.
