### ISSUE TITLE
Bot Group Add Member does not work for Bots created with '_'

### ISSUE THREAD

**Issue by volekthefndwarf** [EQEmu/Server#768]
**Reproduce Steps**
1. Create a Bot with underscore "Mybot_a"
2. Create Bot Group using targeting mechanism (using name variable has similar issue of not finding bot)
3. Create a new bot with underscore in name "Mybot_b"
4. Use Bot Command Add Member:  Target "Mybot_a"  ^bgadd Mybot_b
5. Error: You must [name] a new member as a bot that you own to use this command

Some more context I was able to gather, but not dig into code myself (as my C++ is 15+ years old) 
* Bot constructor automatically runs a name change in constructor that when a bot is Saved makes the Name column change "_" to " ".   
* All bot entries in the database do not get saved with underscore, like mobs in the npc_types table. 
* There may be a way to enclose names to the commands in the client, but typical way I might try that with quotes did not seem to work.

**Comment by Kinglykrab** [comment]
Closing this, can't use underscores in bot names as it causes issues. Have to use camelcase (g.e. KinglysWarriorBot).
