### ISSUE TITLE
Spell Message Range not applying

### ISSUE THREAD

**Issue by MazeEQ** [EQEmu/Server#777]
Dynamically increasing the spellmessage range is not taking effect with the rule:

Range:SpellMessages .

The default range shows as 75 in the source, but the range is moreso 50 units.

**Comment by mackal** [comment]
There are some ranges enforced on the client ... this maybe one of them. At least in the situation you're seeing it.

**Comment by MazeEQ** [comment]
Roger. 

Will delve deeper into this then.

**Comment by Kinglykrab** [comment]
Seems client-sided and not something we can fix with a source change, closing for now unless we find more information in the future.
