### ISSUE TITLE
Fast (Out-Of-Combat) Regen Is Always False

### ISSUE THREAD

**Issue by mthogan** [EQEmu/Server#786]
In client.h "bool CanFastRegen() const { return ooc_regen; }". In client.cpp "ooc_regen = false;" and then it is never updated with the rule_value (or at least I assume it was supposed to get Character:RestRegenEnabled).
And obviously CanFastRegen() is used in client_mods.cpp to determine regen calculation. Client::CalcHPRegen, Client::CalcManaRegen, Client::CalcEnduranceRegen ... it effectively looks like it is returning false always.

**Comment by mackal** [comment]
https://github.com/EQEmu/Server/blob/5e03d977d6e7d89903d7bb59d2c3fbb2d55a9c3c/zone/client_process.cpp#L1936

It's set in Client::CaclRestState().

**Comment by mackal** [comment]
Works on PEQ and my test server.

**Comment by mthogan** [comment]
Hmm. Alright. Will keep tweaking to see what my conflict is. Thanks again.
