### ISSUE TITLE
"You are currently not allowed..."

### ISSUE THREAD

**Issue by viticius** [EQEmu/Server#809]
I used the Windows server install and followed the instructions but am having issues logging in. I see the server listing in Server Select with all of the other EqEmu servers but when I try to login I get..

"You are currently not allowed to login to the server because this IP has a temporary block on it. Please try again later."

I thought it was an isolated issue being that I am the one hosting the server so I asked my friend to try to login and he receives the same error. I even tried using the localhost login and got the same error. 

Any help is appreciated!

**Comment by SecretsOTheP** [comment]
What's your server's name on the list?

**Comment by viticius** [comment]
> e

Cam&Trav's Play Land --- For lack of a better name. :)

**Comment by HelixCoder** [comment]
I confirmed on a local host vm that this is happening on latest build, you need to run perl update on server in server directory.  This is currently a known broken build issue according to @Akkadius over in discord chat.

to temp fix:
`perl eqemu_server.pl windows_server_download `

this will pull the latest stable and you should be able to log in after that.

You can find more about updating the server here:
https://github.com/EQEmu/Server/wiki/Updating-Server-Assets#assets-menu

**Comment by viticius** [comment]
> 
> 
> I confirmed on a local host vm that this is happening on latest build, you need to run perl update on server in server directory. This is currently a known broken build issue according to @Akkadius over in discord chat.
> 
> to temp fix:
> `perl eqemu_server.pl windows_server_download `
> 
> this will pull the latest stable and you should be able to log in after that.
> 
> You can find more about updating the server here:
> https://github.com/EQEmu/Server/wiki/Updating-Server-Assets#assets-menu

Wow.... that fixed it.
