### ISSUE TITLE
Bots not Attacking while in Guard

### ISSUE THREAD

**Issue by braindisconnect** [EQEmu/Server#811]
This was fixed and now its back. Commenting out Lines 2297, 2299, and 2300 will "fix" this.  Line 2299 was commented out so they can break mez on ^attack.  Line 2300 is the main cultprit for attacking and clearing hate list.

                // Let's check if we have a los with our target.
                // If we don't, our hate_list is wiped.
                // Else, it was causing the bot to aggro behind wall etc... causing massive trains.
                if (/*guard_mode ||*/
                        !tar->IsNPC() ||
                        /*tar->IsMezzed() ||*/
                        /*(!tar->GetHateAmount(this) && !tar->GetHateAmount(leash_owner) && !leash_owner->AutoAttackEnabled()) ||*/
                        lo_distance > BOT_LEASH_DISTANCE ||
                        tar_distance > BOT_LEASH_DISTANCE ||
                        (!CheckLosFN(tar) && !leash_owner->CheckLosFN(tar)) ||
                        !IsAttackAllowed(tar))
                {

**Comment by Uleat** [comment]
Bot AI rework has addressed this issue.
