### ISSUE TITLE
Add New Methods To Override Zone XP & AA XP Mods & XP Loss On Death

### ISSUE THREAD

**Issue by CoreAutomation-JD** [EQEmu/Server#812]
**Proposal:** It be would be very handy to be able to set an individual XP, AAXP, LB/Blue/White/Yellow/Red modifiers along with turning on/off XP loss on death. This would override global rules. 

**Case:** I have several instances where I want to give much lower XP rates and also cause a player to lose XP on death, while all other zones should use values set by global rules.

**Solution:** Add new methods such as:

-SetTemporaryXPMod()
-SetTemporaryAAXPMod()
-SetTemporaryLightBlueXPBonusMod()
-SetTemporaryBlueXPBonusMod()
-SetTemporaryWhiteXPBonusMod()
-SetTemporaryYellowXPBonusMod()
-SetTemporaryRedXPBonusMod()
-SetTemporaryDeathXPPenalty()

**Comment by KinglyKrab** [comment]
Added here: https://github.com/EQEmu/Server/pull/813
