### ISSUE TITLE
Case To Create AA Globals

### ISSUE THREAD

**Issue by CoreAutomation-JD** [EQEmu/Server#815]
**Case:** I would like to be able to give any AA and/or increment its' value based on a specific achievement a player obtains. This achievement would be stored in a data_bucket. The AA would not be restricted by usual means and not appear as trainable by a player.

**Justification:** Currently it is not clear whether or not this is truly doable in a dynamic fashion. Spell Globals are exceptionally useful for progression-based servers. AA Globals would be as well, if not even more so. I do understand certain AA's are gated based on level and current rank, so I assume this would have to stepped over in some fashion. Perhaps in the case of requiring a previous AA those dependencies could also be auto-updated.

**Use:** Player beats a hard encounter and receives a new bucket key/value. A previously unobtainable AA rank will now be able to be trained or, if easier, unlocked for the player. It would most likely be optimal to provide both options.

**Example:** $client->ForceGrantAA(id, rank);

**Comment by mackal** [comment]
I don't really think we need to do anything for this. We should be able to script it all already.

**Comment by CoreAutomation-JD** [comment]
Could you provide an example of how I could provide a player with an AA that is above their level and only obtainable with some sort of flag, be it global or bucket?

**Comment by mackal** [comment]
You would make a "grant only" AA. Look into how we do veteran rewards.

**Comment by CoreAutomation-JD** [comment]
How does this apply to a talent with multiple ranks? Let’s say a character caps out naturally at rank 5 of enhanced aggresssion due to level. 

Does grantable apply to to each rank or only to AA’s with one rank?

**Comment by alimalkhalifa** [comment]
I feel like this is both:

1- A non-standard function (does not exist on live) and
2- A super specific use case

And it seems like a pretty easy one to implement. Maybe user should do the modification on their end for their use and if the feeling is that more people would benefit from this, make a PR?

**Comment by mackal** [comment]
Grant Only flag applies to the whole AA series. So can't do that. Create a new AA.

**Comment by Kinglykrab** [comment]
Closing this for now, if anyone wants to add this functionality later, we can reopen.
