### ISSUE TITLE
Aura's Crash Zone If NPC Depopped/Killed

### ISSUE THREAD

**Issue by CoreAutomation-JD** [EQEmu/Server#816]
In the event the invisible aura npc is depopped or otherwise killed, when a user does any of the following the zone will immediately crash:

1. Die.
2. Gate/Zone/Transport themselves away from the current zone.
3. Remove the Aura buff manually.

This is very easily reproducible. 

Example crash log: https://pastebin.com/XuA80gkF

**Comment by joligario** [comment]
Should be fixed. https://github.com/EQEmu/Server/commit/6f73278cf858935f58d736600e3c4c50aefe044e#diff-2733406edf364dd9a4fc899dfb4c0b7746dd313e20c0de967fb705f938291d7c
