### ISSUE TITLE
Clean up unused DB entries

### ISSUE THREAD

**Issue by Dracovious** [EQEmu/Server#819]
It's probably on a road map somewhere but I am working on setting up a new server and was wondering if it would it be possible for the db to be cleaned up removing obsoleted and unused entities in the database?  I am having to do research to find information from 3-4 years ago no longer apply because something new came out and over wrote it but the original data in the db still exists.

Thanks for the hard work everyone does and looking into this.

**Comment by joligario** [comment]
Need some specifics. What obsolete or unused entities are being left over?
