### ISSUE TITLE
UCS.exe crashes if server shortname+character name exceeds 63 characters.

### ISSUE THREAD

**Issue by Techungry** [EQEmu/Server#820]
Line 604 in ucs/clientlist.cpp declares     char MailBox[64]; If the  value attempted to put into that string is is larger than 63 characters+terminator UCS.exe eventually crashes with the following crash report. When Database::VerifyMailKey is executed and the query there returns 0 results EXCEPTION_ACCESS_VIOLATION occurs.
[ucs_14764.log](https://github.com/EQEmu/Server/files/2823221/ucs_14764.log)
UCS.exe crashes.
[crash_ucs_14764.log](https://github.com/EQEmu/Server/files/2823203/crash_ucs_14764.log)

**Comment by mackal** [comment]
First off, why is your short name stupidly long?

**Comment by Kinglykrab** [comment]
Closing this as it's a non-issue, just can't use super long server short names.
