### ISSUE TITLE
Heroic Adventures (Call of the Forsaken, The Darkened Sea)

### ISSUE THREAD

**Issue by xackery** [EQEmu/Server#825]
This issue can mostly be ignored, as it requires a client that EQEMU currently does not support. As of this writing RoF2 is the latest client EQEMU supports, and these features are for Call of the Forsaken and The Darkened Sea, the next 2 expansions after RoF2. I am documenting my findings however since some of these mechanics could help inspire existing systems, and possibly prepare for the future as well as we evolve the code base.

Heroic Adventures are in a sense a 2.0 to the LDON mission system. It becomes a great path for itemization and experience at ~75+ for those who are geared to take them.

* Call of the Forsaken introduced Heroic Adventures that scale for level 75 and above.
* The Darkened Sea introduced Heroic Adventures that scale for level 95 and above.
* November 2014th a month after The Darkened Sea release date,Guard Hamarn in Ethernere Tainted West Karana would like tales to tell of heroic adventures. Each day he will offer you bonus experience if you do any of four Heroic Adventures from Call of the Forsaken for him.
*   February 15, 2017, Clayton Teek [Daily Adventures] was introduced PoK near the guild lobby zone line. This NPC replaced Guard Hamarn, and allows you to accept Bonus Heroic Adventure tasks that have a 42 hour timer and gives an option to teleport to the Heroic Adventure NPCs easily to accept the related heroic adventure task.
* Heroic Adventures appear in your task window as a timed tasks you have 5 hours to complete.
* These tasks have markers similar to LDoN pointing you to the interactive door to zone you into an instance.
* If you complete the heroic adventure before the timeout, you complete the task, and there is a 3 hour lockout timer to do another to all who participated in the adventure task.
* A new tab appears on tasks called Shared Tasks that let you manage the players actively participating in a task, allowing you to assign and remove them. There are also internal commands, such as /taskadd that you can use for cross-zone player inviting.
* When a player enters the heroic adventure instance, their level is analyzed. I would imagine every player in the zone is iterated through and the highest level player determines how the NPCs will scale. The NPCs will instantly scale (even engaged ones) to be stats of the highest level player instantly, including downscaling NPCs if a higher level player leaves the zone.
* The difficulty of heroic adventures are built to require a top-tiered geared tank of the highest level player in the instance to reasonably take the instance. Seems itemization of the rest of the group is not as important.
* The Min and Max Damage range of NPCs seems to have a large variance, meaning if you are under geared you almost feel hope that you can take on the encounter, until a high damage roll succeeds and your tank loses ~80% of their health in a single round once in a while and potentially wipe the group.
* Hitpoints of NPCs, especially trash, seem to be reasonably low compared to equivalent content. 
* NPC population and general zone size of these adventures seem relatively compact. The pathing appears to be built to give pullers a bit of an annoyance, but nothing extreme if you wait for NPCs to roam.
* Each heroic adventure typically has a final boss to kill at the end, and is the most significant HP NPC of the zone, as expected.
* No NPCs respawn inside the instance.
* Each PH in each instance appears to have a rare chance to be a rare boss monster with bonus loot.
* All NPCs appear to have a rare drop of Rk II spells for your provided level.
* All Rares inside of an HA should be Findable [using Ctrl-F] - Auger
* The old spawn rates were a flat 30% for every HA. The new spawn rates for the original HAs are between 30-70%. The new Hate Rising HAs are all close to 20% because of how much quicker they are to complete. - Auger
* A coordinated group should be able to farm Rares inside of HAs slightly faster than you could in an open-world zone. Average groups will be a bit slower. Obviously, a solo player will be lagging behind open-world zone farm times. We're happy with that current comparison. - Auger
* Mark of Valor is rewarded for CotF heroic adventures
* Piece of Eight is rewarded for TDS heroic adventures

**Comment by mackal** [comment]
These don't actually require a newer client to be supported (Ignoring zones not existing) they're just expansion into what shared tasks can do really.

**Comment by mackal** [comment]
Fun fact. All the control NPCs in CotF HAs are named after Modest Mouse songs :P

**Comment by xackery** [comment]
Yeah, the items, the currency, the merchants, the zones, most of what the baseline heroic adventures require won't work so well with RoF2 and before, but the core mechanics could probably be replicated with RoF2 and before. Possibly even without a lot of alteration of the current system. I assume DoN's mission system is more akin to LDoN's, where the group is locked and has level reqs and not dynamically scaled the moment a player zones in like HA's work though.. Or did they refit ldon/don after cotf/tds introduction?

**Comment by mackal** [comment]
Besides the fact shared tasks aren't implemented at all ...

The zones are also modified by dynamic objects that will block off paths etc.

**Comment by xackery** [comment]
I see.. Looks like shared tasks were originally introduced in Omens of War-ish era? So, this can be something I can research among Fellowship as I'm testing to see implementing it.

**Comment by Kinglykrab** [comment]
Closed for now, can reopen in the future if any work is done related to this.
