### ISSUE TITLE
Column 'notes' gets cleared in table 'rule_values'

### ISSUE THREAD

**Issue by wmrojer** [EQEmu/Server#835]
Since rule_values are updated to the database with `REPLACE INTO rule_values (ruleset_id, rule_name, rule_value) VALUES(%d, '%s', '%s')` the column 'notes' gets cleared for the active rule set every time you start the server. (Replace into deletes any existing row before inserting a new one)

Update should probably be done with `UPDATE rule_values SET rule_value='%s' WHERE ruleset_id=%d and rule_name='%s'`. 
(But this won't work if new rules are added this way, but I can't see that it does.)

**Comment by Akkadius** [comment]
Sounds like we need to take more of a "insert into x on duplicate key update x" approach for this one

**Comment by Uleat** [comment]
I am working on a branch where this is already fixed.

I'll close this issue once it gets merged.
