### ISSUE TITLE
The rules tradeskill skillup modifiers should probably be Real instead of Int

### ISSUE THREAD

**Issue by wmrojer** [EQEmu/Server#836]
Seeing that the variable the rules for tradeskill skillup modifiers is read into is a float and the comment "// Remember: skillup_modifier is (float). Lower is better" in the code and the way the skillup chance is calculated the rules should probably be stored and read as RULE_REAL instead of RULE_INT.
Default values are between 1 and 4 and the note says lower is better. So not many different steps to increase the chance without the rule being a float.

The affected rules are:
TradeskillUpAlchemy, TradeskillUpBaking, TradeskillUpBlacksmithing, TradeskillUpBrewing,
TradeskillUpFletching, TradeskillUpJewelcrafting, TradeskillUpMakePoison, TradeskillUpPottery,
TradeskillUpResearch, TradeskillUpTinkering.

**Comment by wmrojer** [comment]
And there isn't even a rule for Tailoring. Maybe add that one or it's hard coded to 2.0

**Comment by Aeadoin** [comment]
Resolved in #2674
