### ISSUE TITLE
Focus effect messages sent with wrong message type.

### ISSUE THREAD

**Issue by wmrojer** [EQEmu/Server#837]
Focus effect text is sent to the client as MT_Spells instead of MT_FocusEffect. 
In method Client::GetFocusEffect in spell_effects.cpp and method Mob::DoCastSpell in Spells.cpp.
There could be more places, but that's the ones I've found.

This makes it impossible to filter out those message on the client.

**Comment by Aeadoin** [comment]
I believe this can be closed, I searched for any other instances where Focus effect messages sent with wrong message type... and couldn't find any.

Focus Effects can be filtered out now also per #2447
