### ISSUE TITLE
#scaling determination

### ISSUE THREAD

**Issue by freewindkiteflyer** [EQEmu/Server#844]
Ran into a problem with #scale today..... with current way code is written you have to remove capital letters and any other markings that might flag it as a "Named" before it'll allow the script to check for "raid_boss" tag otherwise the "Named" takes precedence.

**Comment by Akkadius** [comment]
Fixed by https://github.com/EQEmu/Server/commit/6739eea78bbc0f293c8faacbb07c38a2b9b73f75
