### ISSUE TITLE
eqemu_config json full example shows no example of the below

### ISSUE THREAD

**Issue by mixxit** [EQEmu/Server#845]
WorldAddress = _root["server"]["world"].get("address", "").asString();
	LocalAddress = _root["server"]["world"].get("localaddress", "").asString();

Could be confusing behind a nat

**Comment by xackery** [comment]
Which full example are you referring to?  https://github.com/EQEmu/Server/wiki/eqemu_config has this info in it

**Comment by mixxit** [comment]
https://github.com/EQEmu/Server/blob/master/utils/defaults/eqemu_config.json.full

**Comment by mixxit** [comment]
still appears to be missing

**Comment by mixxit** [comment]
Still an issue
