### ISSUE TITLE
Server Not recognizing Internet Connection

### ISSUE THREAD

**Issue by RAVaught** [EQEmu/Server#848]
Using Windows 10 - x64 server installer, the  eqemu_install fails on call to eqemu_server.pl  check_internet_connection(). 

Tested by settting the fail to "return 1"(Line 583) and updater begin running as intended until the .pl file was overwritten by the updater.

**Comment by Akkadius** [comment]
This typically happens on networks that are more ridiculously locked down, not allowing outbound ICMP

**Comment by RAVaught** [comment]
Outbound ICMP is enabled on my firewall and my router. Is there a work around?
