### ISSUE TITLE
ResetAA does not delete AAs from character_alternate_abilities table

### ISSUE THREAD

**Issue by peterigz** [EQEmu/Server#856]
Using #resetaa does not actually remove entries from character_alternate_abilities as well so when the character logs back in all their AA are back, plus their total AAs to spend has increased because they all got refunded. Comparing to older versions of the function there's no longer a call to database.DeleteCharacterAAs(this->CharacterID()); so maybe that just needs to be put back in somewhere?

Relevant function: https://github.com/EQEmu/Server/blob/master/zone/aa.cpp#L459

**Comment by mmcgarvey** [comment]
This appears to have been fixed by #1681
