### ISSUE TITLE
quest::say() results in garbage on the client side. 

### ISSUE THREAD

**Issue by pboyd04** [EQEmu/Server#870]
Quest popups work fine, however the say command results in what looks like binary or unicode printed on the client chat window. See the attached for what it looks like.

I'm running Titanium client if it helps. And I'm running the server on Fedora 28.

![EQemu](https://user-images.githubusercontent.com/594097/61334806-bdcf9b80-a7f0-11e9-8029-3cbe5a9ae86d.png)

**Comment by mackal** [comment]
Update, this should be fixed.

**Comment by pboyd04** [comment]
Ok just updated assets and now I don't get any dialog... Do I need to recompile the server source too?

**Comment by mackal** [comment]
Looks like Tit might still be broken, not sure why, looks like it should all be fine.

**Comment by pboyd04** [comment]
I've played with it a bit more. On rare occasions it works. Other times it's garbage as above, sometimes it looks like it dumps a SQL table entry for a spell, and sometimes it doesn't print anything. It looks like it's grabbing random RAM. Am I correct that the chat stuff comes from the ucs process? If so I'll try slapping valgrind on it and look for memory errors.

**Comment by mackal** [comment]
It's because we're encountering undefined behavior and the compiler is having fun :P

**Comment by mackal** [comment]
This should be resolved with #871 being merged. Let me know if you're still having issues.

**Comment by Akkadius** [comment]
Closing in the interim, but if issues still persist lets follow up
