### ISSUE TITLE
Hate Override Handled Late

### ISSUE THREAD

**Issue by Shendare** [EQEmu/Server#873]
https://github.com/EQEmu/Server/blob/9ac15d7a4ba348f271fcb88c2fb836c688d6c653/zone/aggro.cpp#L1189

The field named "HateAdded" is properly handled as actually an override for the amount of hate generated by casting a spell, but it's applied after all the expensive calculations have already been done for how much hate to generate, which end up just getting thrown away.

This check should be one of the first instead of the last.

**Comment by Aeadoin** [comment]
Fixed under #2466
