### ISSUE TITLE
Hate Override Not Handled for Healing Spells

### ISSUE THREAD

**Issue by Shendare** [EQEmu/Server#874]
https://github.com/EQEmu/Server/blob/9ac15d7a4ba348f271fcb88c2fb836c688d6c653/zone/aggro.cpp#L1212

The HateAdded field is an override for the amount of hate generated by a spell. It's checked for detrimental spells in CheckAggroAmount(), but not checked for healing spells.

Adding handling for HateAdded in CheckHealAggroAmount() would be useful for customized servers.

**Comment by Aeadoin** [comment]
Can assign this to me, I'll look at it.
