### ISSUE TITLE
2HB animation resembles 2HS

### ISSUE THREAD

**Issue by Isaaru** [EQEmu/Server#884]
```
case EQEmu::item::ItemType2HBlunt: // 2H Blunt
			skillinuse = EQEmu::skills::Skill2HBlunt;
			type = anim2HSlashing; //anim2HWeapon
			break;
```

and

```
case EQEmu::skills::Skill2HBlunt: // 2H Blunt
			type = anim2HSlashing; //anim2HWeapon
			break;
```

**Comment by dencelle** [comment]
https://github.com/EQEmu/Server/blob/7b4908957d7f9aee02e1e2095160b768bc505100/zone/attack.cpp#L75
just so this is a bit easier to reference, although, i'm not exactly sure what animation id 2hb weapons should have

**Comment by Isaaru** [comment]
anim2HWeapon

**Comment by dencelle** [comment]
https://github.com/EQEmu/Server/commit/3ec1c894eef86f8a0e6b2304c721dc72e246851a
this is when it was changed from anim2HWeapon to anim2HSlashing... so, we have @Isaaru saying it should be one thing and @ukmeth0d saying it should be another...

**Comment by Isaaru** [comment]
It changed with the introduction of hammers, I guess it looked silly slamming to top of a hammer into someone. However, many prefer the old 2hb animation and at the least should be a rule.  Maybe, have 2 separate ones that we can choose depending on the type of weapon?

2HB (New)
2HB (Old)

**Comment by Isaaru** [comment]
I propose simply making a rule for this. Allow the server owners to choose original 2hb animation or the 2hs style.

**Comment by prestanneth** [comment]
animation 4 (2hb) is the same as 2 piercing under new models which is a piercing animation visually.
(hence why it was changed to 5 above when really it was making an assumption on user preferences)

If you swap models (under options before logging into game), to turn off luclin models, 2hb becomes 
 the proper 2hnd blunt whack visually which is more correct than 
the downwards slash that is live on emu today when new models are on.
( If you reverse the above change first that is )

So, essentially this is not server based but client based, more specifically user preference based on a per race basis.

The main issue with the code is, its not checking what models are loaded to select the correct animation and just assuming everyone uses new models only.

**Comment by Isaaru** [comment]
I don't use new models and never have.
This can be closed. I made the change on my end already.
