### ISSUE TITLE
Old school poison does not work as on live.

### ISSUE THREAD

**Issue by noudess** [EQEmu/Server#912]
Old school poison needs to be changed to match live.

**Apply:**

Match live.  Can apply regardless of weapons equipped, but will not proc until a 1hp weapon is used to attack.

**Proc:**

Proc's on first attack that lands (hits or miss) from a piercing weapon (100%) then is removed. Proc happens after all other procs.

Zoning:

Poison is gone if apply and zone before using it.

Special Rule:

I will add a rule that allows the current eqemu implementation to exist.  The only differences from above will be that the proc remains from when you apply until you zone, and the % to proc will be less.  (Basically today's eqemu mechanism for old poisons, but this will be in a rule and the rule will default to live behavior).

**Comment by mackal** [comment]
One thing to investigate: Does SE_SkillAttack (193) using 1hp attack also proc. Only test case I can find seems to be Secret Blade disc procs 1hp attacks, but that's level 109 which my rog isn't :(

https://spells.eqresource.com/spells.php?id=56315


This could be tested with 2 non 1hp weapons I guess.

**Comment by mackal** [comment]
Fixed with #915
