### ISSUE TITLE
bug in older sql update. Can be edited?

### ISSUE THREAD

**Issue by prestanneth** [EQEmu/Server#927]
2015_02_02_logsys_packet_logs_with_dump.sql contains a bug.
REPLACE INTO `logsys_categories` (`log_category_id`, `log_category_description`) VALUES ('41', 'Packet: Server -> Client With Dump'); 
REPLACE INTO `logsys_categories` (`log_category_id`, `log_category_description`) VALUES ('42', 'Packet: Server -> Client With Dump'); 

42 should read "Packet: Client -> Server With Dump".

**Comment by joligario** [comment]
Sure, feel free to submit a PR

**Comment by prestanneth** [comment]
closing, uleat has fixed old sql file today.
