### ISSUE TITLE
crypto_pwhash_scryptsalsa208sha256_str() Login server issue

### ISSUE THREAD

**Issue by prestanneth** [EQEmu/Server#929]
Using a local login server.
I know it happens to me , and a couple of others so i assume its the same for everyone whose hosting an updated login server.

libsodium's crypto_pwhash_scryptsalsa208sha256_str() used in eqcrypt_scrypt
returns a zero terminated string ( \0 ).

Functions like CreateLoginDataWithID() that have the password run through the above on scrypt end up with the pw containing this additional zero terminator at end.
The EscapeString() function used before database entry on this new account sees the zero terminator in
``    case '\x00':
            ret += "\x00";
``
and adds the \x00 ret value to the string it "built" then passes it to database.
Thereafter you cant login as the pw dont match, unles you manually manipulate in database.

I mentioned on discord but it got a bit lost in messages so posting here so is somewhere visible for further investigation.

I have tried a few methods and ended up using below to just clean the end of pw string before being passed in.

 loginserver/database.cpp | 3 ++-
 1 file changed, 2 insertions(+), 1 deletions(-)
```cpp
bool Database::CreateLoginDataWithID(	const std::string &in_account_name,	const std::string &in_account_password,	const std::string &loginserver,	unsigned int id)
{
	if (id == 0) {
		return false;
	}

+	std::string password = EscapeStringPW(in_account_password);
 	auto query = fmt::format(
 		"INSERT INTO login_accounts (id, source_loginserver, account_name, account_password, account_email, last_login_date, last_ip_address, created_at) "
 		"VALUES ({0}, '{1}', '{2}', '{3}', 'local_creation', NOW(), '127.0.0.1', NOW())",
 		id,
 		EscapeString(loginserver),
 		EscapeString(in_account_name),
-		EscapeString(in_account_password)
+		EscapeString(password)
 	);
		auto results = QueryDatabase(query);

	return results.Success();
}
	
```	
 common/string_util.h | 1 +
 1 file changed, 1 insertion(+)
```cpp
 std::string EscapeString(const std::string &s);
+std::string EscapeStringPW(const std::string &s);
 bool StringIsNumber(const std::string &s);
 
```	
	

 common/string_util.cpp | 17 +++++++++++++++++
 1 file changed, 17 insertions(+)

```cpp
+std::string EscapeStringPW(const std::string &s) {
+	std::string ret;
+	size_t sz = s.length();
+	for (size_t i = 0; i < sz; ++i) {
+		char c = s[i];
+		switch (c) {
+		case '\x00':
+			ret += (i + 1 == sz) ? "" : "\\x00";
+			break;
+		default:
+			ret.push_back(c);
+			break;
+		}
+	}
+	return ret;
+}
+
```

**Comment by Akkadius** [comment]
Thanks @prestanneth - I'll take a look at this one

**Comment by Akkadius** [comment]
Fixed via https://github.com/EQEmu/Server/commit/c90bed9f692251598a28ea5a46dd5ed04df0b797
